/*
 * AI Explorer Academy ‚Äî cards-nl.js
 * Volledig herschreven Explorer Card-bibliotheek (29 kaarten, redactieversie).
 * Kernfilosofie in elke kaart: AI is het vertrekpunt, niet het eindpunt ‚Äî het kind houdt de regie.
 * Vaste velden (id, superpower, niveau, categorie, werkvorm, competenties, zintuigen, tijdsduur)
 * zijn identiek aan de bron; alle vrije tekstvelden zijn opnieuw geschreven. Nieuw veld: bonus.
 * Volgorde: Ontdekken ‚Üí Samenwerken ‚Üí Controleren ‚Üí Verbeteren ‚Üí Regie Voeren, oplopend niveau.
 */
window.CARDS_NL = [
  {
    "id": "ontdekken-01",
    "titel": "De Waarom-Machine",
    "superpower": "Ontdekken",
    "niveau": 1,
    "categorie": "Onderzoek",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Nieuwsgierigheid", "AI Bewustzijn"],
    "uitdaging": "Waarom is de lucht blauw? Waarom plakt plakband? Ergens in jouw hoofd zit een vraag waar nog nooit iemand antwoord op gaf. Vandaag laat je hem los.",
    "missie": "Aan het eind heb je een antwoord op jouw allergekste waarom-vraag ‚Äî √©n heb je zelf besloten of je het gelooft.",
    "stappen": [
      "Bedenk drie waarom-vragen waar je √©cht benieuwd naar bent.",
      "Kies de gekste als je kampioensvraag.",
      "Stel hem samen met een volwassene aan de AI.",
      "Speel wetenschapper: vraag de AI hoe zeker die het weet.",
      "Beslis zelf: geloof ik dit, of wil ik meer weten?"
    ],
    "samenwerken_met_ai": "De AI is jouw antwoord-hulpje: het geeft een startpunt. Maar jij bent de vragensteller √©n de keurmeester ‚Äî jij beslist of het antwoord goed genoeg is.",
    "ai_prompt": "Je bent een vrolijke uitleg-hulp voor een kind van [leeftijd] jaar. Het kind heeft een waarom-vraag: [jouw waarom-vraag]. Antwoord in maximaal 4 korte, simpele zinnen. Zeg er eerlijk bij hoe zeker je bent: heel zeker, beetje zeker, of eigenlijk weet niemand het. Stel daarna √©√©n nieuwsgierige wedervraag terug, zodat het kind zelf verder denkt. Neem het denken niet over.",
    "eigen_keuze": "Welke van je drie vragen verdient de titel 'gekste vraag ooit' ‚Äî en waarom juist die?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Jij mag √°lles vragen ‚Äî en jij bepaalt zelf of je het antwoord gelooft.",
    "reflectievraag": "Wat doe jij als de AI zegt 'dat weet ik niet zeker' ‚Äî en wie beslist er dan wat jullie geloven?",
    "zintuigen": ["vertellen", "luisteren"],
    "begeleiders_tip": "Laat het kind eerst hardop raden v√≥√≥r de AI antwoordt. Vraag: \"Wat denk jij zelf dat het antwoord is?\" Let erop dat het kind niet klakkeloos knikt bij het AI-antwoord ‚Äî twijfel is hier winst.",
    "bonus": "Nog een keer? Stel nu een waarom-vraag over jezelf (waarom moet ik gapen als iemand anders gaapt?) ‚Äî en kijk of de AI over j√≥√∫ net zo zeker durft te zijn."
  },
  {
    "id": "ontdekken-02",
    "titel": "De Dieren-Mixmachine",
    "superpower": "Ontdekken",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15‚Äì20 min",
    "competenties": ["Nieuwsgierigheid", "Creativiteit"],
    "uitdaging": "Ergens diep in de jungle leeft een beest met stekels √©n vleugels. Niemand heeft het ooit gezien. Logisch ‚Äî het bestaat pas als jij het vandaag verzint.",
    "missie": "Aan het eind heb je een tekening van een gloednieuw dier dat nog nergens bestond ‚Äî met een naam, een superkracht en een eigen geluid.",
    "stappen": [
      "Kies twee dieren die nooit samen op √©√©n foto staan.",
      "Vraag de AI om er √©√©n mix-dier van te maken.",
      "Speel dieren-uitvinder: verander minstens √©√©n ding aan het AI-idee.",
      "Teken het dier precies zoals j√≠j het voor je ziet.",
      "Verzin het geluid van je dier en doe het hardop na."
    ],
    "samenwerken_met_ai": "De AI is je idee√´n-fabriek en gooit er een startdier uit. Jij bent de uitvinder die beslist hoe het dier er √©cht uitziet, klinkt en heet.",
    "ai_prompt": "Speel dat je een gekke dierenfabriek bent voor een kind van [leeftijd] jaar. Mix een [dier 1] met een [dier 2] tot √©√©n nieuw dier. Geef het een grappige naam en vertel in maximaal 4 korte, vrolijke zinnen wat het kan. Vraag daarna wat het kind z√©lf aan het dier wil veranderen ‚Äî en beschrijf niets meer totdat het kind heeft geantwoord. Het dier is van het kind, niet van jou.",
    "eigen_keuze": "Wat verander jij aan het AI-dier: de kop, de kleur, de superkracht ‚Äî en waarom juist d√°t?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî plus papier en stiften",
    "wat_leer_je": "AI kan je op idee√´n brengen, maar jouw fantasie maakt het dier pas echt.",
    "reflectievraag": "Van wie is dit dier nu eigenlijk: van jou of van de AI ‚Äî en waaraan zie je dat op je tekening?",
    "zintuigen": ["luisteren", "tekenen", "vertellen"],
    "begeleiders_tip": "Laat het kind eerst zelf schetsen v√≥√≥r je de AI-beschrijving voorleest. Vraag: \"Wat had jij bedacht dat de AI niet zag?\" Let op dat het kind de AI-versie niet gaat na-tekenen ‚Äî de afwijking is het goud.",
    "bonus": "Nog een keer? Mix nu drie dieren tegelijk ‚Äî of laat een huisgenoot de twee dieren kiezen, zodat jij met een onmogelijke combinatie zit."
  },
  {
    "id": "ontdekken-03",
    "titel": "Jacht op het Nepwoord",
    "superpower": "Ontdekken",
    "niveau": 3,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Nieuwsgierigheid", "Kritisch Denken"],
    "uitdaging": "Er bestaan woorden zo raar dat ze verzonnen lijken. En soms verzint de AI er stiekem eentje bij. Wie houdt hier wie voor de gek?",
    "missie": "Aan het eind heb je een lijstje met bewezen echte woorden, minstens √©√©n betrapte twijfel ‚Äî en √©√©n splinternieuw woord van jezelf.",
    "stappen": [
      "Vraag de AI om drie superrare bestaande woorden met betekenis.",
      "Wijs als woord-detective aan welk woord het meest nep voelt.",
      "Zoek elk woord op in een echt woordenboek.",
      "Streep door wat niet klopte en kroon wat echt bleek.",
      "Verzin zelf √©√©n nieuw woord dat eigenlijk zou m√≥√©ten bestaan."
    ],
    "samenwerken_met_ai": "De AI levert de woorden aan, jij bent de detective met het woordenboek. Niet de AI maar jouw controle bepaalt wat echt telt.",
    "ai_prompt": "Je helpt een kind van [leeftijd] jaar dat woord-detective speelt. Geef 3 heel rare maar bestaande Nederlandse woorden met hun betekenis, elk met een grappige voorbeeldzin. Houd elke uitleg onder de 2 zinnen, simpel en vriendelijk. Twijfel je bij een woord of het echt bestaat? Zeg dat er eerlijk bij ‚Äî het kind gaat je toch controleren.",
    "eigen_keuze": "Welk woord verdenk je het meest ‚Äî en waar zit hem dat in: de klank, de betekenis of je onderbuik?",
    "ai_tools": "een AI-chat plus een echt woordenboek (papier of online)",
    "wat_leer_je": "Controleren is geen corvee maar een speurtocht ‚Äî en jij bent er goed in.",
    "reflectievraag": "Hoe voelde het om de AI te controleren in plaats van te geloven ‚Äî en wie had uiteindelijk het laatste woord?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "AI verzint soms echt woorden of betekenissen. Vier het luid als dat gebeurt: \"Jij hebt een AI betrapt!\" Vraag: \"Waaraan rook je dat dit woord niet klopte?\" Let erop dat het kind het woordenboek zelf hanteert.",
    "bonus": "Nog een keer? Draai het om: verzin zelf twee nepwoorden en √©√©n echt woord, en test of de volwassene ‚Äî of de AI! ‚Äî de nepper eruit pikt."
  },
  {
    "id": "ontdekken-06",
    "titel": "De Geluidenjager",
    "superpower": "Ontdekken",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo", "Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Nieuwsgierigheid", "AI Bewustzijn"],
    "uitdaging": "Ssst. Doe je ogen dicht. Tel de geluiden om je heen. Drie? Vier? Een echte geluidenjager vindt er tien ‚Äî zonder √©√©n scherm.",
    "missie": "Aan het eind heb je tien buitgemaakte geluiden op je jachtlijst ‚Äî en weet je welk geluid geen enkele computer kan namaken.",
    "stappen": [
      "Sluip naar buiten of naar een open raam; schermen blijven binnen.",
      "Jaag als geluiden-spion op tien verschillende geluiden.",
      "Teken of schrijf elke vangst op je jachtlijst.",
      "Kies het geluid dat een computer nooit zou kunnen namaken.",
      "Bespreek daarna pas ‚Äî als jij dat wilt ‚Äî je buit met de AI."
    ],
    "samenwerken_met_ai": "Tijdens de jacht is de AI er niet bij: jouw oren doen al het werk. Pas achteraf mag de AI meepraten over jouw buit ‚Äî als napraat-hulpje, niet als jager.",
    "ai_prompt": "Ik ben [leeftijd] jaar en heb net buiten, zonder scherm, deze geluiden gevangen: [jouw lijstje]. Jij bent mijn napraat-maatje. Kies uit mijn lijst het geluid dat een computer het moeilijkst kan namaken en leg in maximaal 3 simpele zinnen uit waarom. Wees eerlijk als je twijfelt. Vraag mij daarna welk geluid √≠k het mooist vond ‚Äî mijn oren waren erbij, die van jou niet.",
    "eigen_keuze": "Welk geluid van je lijst zou je willen bewaren als het allerlaatste geluid op aarde?",
    "ai_tools": "geen AI nodig ‚Äî dit doe je met je eigen oren in de echte wereld (napraten mag daarna)",
    "wat_leer_je": "Jouw oren vangen dingen op die geen enkele computer kan waarnemen.",
    "reflectievraag": "Wat hoorde jij dat een AI nooit had kunnen horen ‚Äî en wat zegt dat over wie er op pad moet: jij of de computer?",
    "zintuigen": ["luisteren", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Begin met √©√©n minuut samen muisstil zijn ‚Äî dat is voor kinderen al een avontuur. Vraag: \"Welk geluid hoorde je nu pas voor het eerst?\" Let erop dat het scherm pas n√° de jacht tevoorschijn komt.",
    "bonus": "Nog een keer? Jaag nu in het donker, of op de tien z√°chtste geluiden die je kunt vinden ‚Äî die zijn het moeilijkst te vangen."
  },
  {
    "id": "ontdekken-04",
    "titel": "Kapitein van de Idee√´n-Storm",
    "superpower": "Ontdekken",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Nieuwsgierigheid", "Creativiteit", "Zelfstandig Oordelen"],
    "uitdaging": "Tien idee√´n krijgen is makkelijk. Negen ervan overboord gooien ‚Äî d√°t is kapiteinswerk. Durf jij te kiezen?",
    "missie": "Aan het eind heb je √©√©n zelfgekozen idee echt gebouwd met spullen uit huis ‚Äî en negen idee√´n vol overtuiging geschrapt.",
    "stappen": [
      "Vraag de AI om tien bouwidee√´n met spullen uit huis.",
      "Streep als kapitein negen idee√´n door ‚Äî zonder spijt.",
      "Kies het idee dat j√≥√∫ het meest kriebelt, niet het 'beste'.",
      "Bouw het en verander onderweg alles wat jij beter vindt.",
      "Inspecteer je maaksel: wat werd er mooier dan gepland?"
    ],
    "samenwerken_met_ai": "De AI is je idee√´n-storm: die blaast tien kanten op. Jij bent de kapitein die de koers kiest ‚Äî de AI heeft niets te zeggen over welk idee wint.",
    "ai_prompt": "Een kind van [leeftijd] jaar zoekt bouwinspiratie. Geef precies 10 genummerde knutsel- of bouwidee√´n met gewone spullen uit huis, elk in √©√©n korte zin. Wijs geen favoriet aan en zeg niet welk idee het beste is ‚Äî het kind is de kapitein die kiest. Daarna is je werk klaar: geen extra tips, tenzij het kind erom vraagt.",
    "eigen_keuze": "Welk idee koos je ‚Äî en waarvan won het het idee dat 'handiger' leek?",
    "ai_tools": "een AI-chat voor de idee√´n ‚Äî het bouwen doe je zelf",
    "wat_leer_je": "Kiezen is een superkracht: uit tien idee√´n durven zeggen 'deze ‚Äî en de rest niet'.",
    "reflectievraag": "Wat was moeilijker: idee√´n krijgen of idee√´n weggooien ‚Äî en wie kan dat weggooien beter, jij of de AI?",
    "zintuigen": ["kijken", "bouwen", "onderzoeken"],
    "begeleiders_tip": "Stuur niet naar het 'beste' idee, ook niet met je wenkbrauwen. Vraag: \"Welk idee blijft er in je hoofd zeuren?\" Let erop of het kind kiest met het hart ‚Äî dat is precies de bedoeling.",
    "bonus": "Nog een keer? Laat de AI nu tien expres slechte idee√´n geven ‚Äî en maak van het allerslechtste idee t√≥ch iets goeds."
  },
  {
    "id": "ontdekken-05",
    "titel": "Expeditie Zonder Stroom",
    "superpower": "Ontdekken",
    "niveau": 5,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "20‚Äì30 min",
    "competenties": ["Nieuwsgierigheid", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Columbus had geen AI. Jouw overgrootmoeder ook niet. Toch ontdekten zij meer dan de meeste mensen m√©t telefoon. Vandaag test je hun geheim.",
    "missie": "Aan het eind heb je drie echte ontdekkingen gedaan met alleen je eigen zintuigen ‚Äî en zelf beslist of AI er achteraf nog iets aan mag toevoegen.",
    "stappen": [
      "Leg elk scherm weg en benoem jezelf tot expeditieleider.",
      "Speur binnen of buiten naar drie dingen die je altijd voorbijloopt.",
      "Bestudeer ze als ontdekkingsreiziger: lang en van dichtbij.",
      "Teken of onthoud wat je nog nooit eerder was opgevallen.",
      "Beslis pas daarna: mag AI nog iets toevoegen, of was dit compleet?"
    ],
    "samenwerken_met_ai": "Op deze expeditie ga je bewust zonder AI op pad ‚Äî dat is de hele kunst. Achteraf ben jij degene die beslist of de AI √ºberhaupt nog aan het woord komt.",
    "ai_prompt": "Alleen voor achteraf, als jij dat wilt: Ik ben [leeftijd] jaar en heb net op eigen kracht, zonder scherm, dit ontdekt: [jouw drie ontdekkingen]. Geef me g√©√©n uitleg en g√©√©n antwoorden. Stel me alleen 3 korte, nieuwsgierige vragen die me n√≥g beter laten kijken. Mijn ontdekking blijft van mij.",
    "eigen_keuze": "Vraag je achteraf nog iets aan de AI, of houd je deze ontdekking helemaal voor jezelf ‚Äî en waarom?",
    "ai_tools": "geen AI nodig ‚Äî dit doe je in de echte wereld",
    "wat_leer_je": "De beste ontdek-machine die bestaat, zit al in jouw hoofd.",
    "reflectievraag": "Wanneer maakt AI een ontdekking groter, en wanneer juist kleiner ‚Äî en wie hoort dat per keer te bepalen?",
    "zintuigen": ["kijken", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Doe zelf mee met schermen weg ‚Äî kinderen voelen het meteen als dit niet eerlijk is. Vraag: \"Wat zag je pas toen je langer bleef kijken?\" Let op het slotmoment: de keuze 'AI erbij of niet' moet √©cht van het kind zijn.",
    "bonus": "Nog een keer? Doe de expeditie op een plek die je 'saai' vindt ‚Äî de gang, de schuur, de parkeerplaats. Saai bestaat niet voor echte ontdekkers."
  },
  {
    "id": "samenwerken-01",
    "titel": "Het Teken-Maatje",
    "superpower": "Samenwerken",
    "niveau": 1,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Samenwerken met AI", "Creativiteit"],
    "uitdaging": "Wit papier. Potlood klaar. En dan... niks. Iedereen kent dat lege-blad-gevoel. Maar jij hebt vanaf vandaag een maatje dat altijd een startidee heeft.",
    "missie": "Aan het eind heb je een tekening die begon met een AI-idee ‚Äî maar vol zit met dingen die alleen jij kon verzinnen.",
    "stappen": [
      "Vraag je teken-maatje (de AI) om √©√©n grappig tekenidee.",
      "Teken het startidee zo goed als jij kunt.",
      "Word geheim versier-agent: smokkel er drie eigen dingen bij.",
      "Verzin een titel die de AI nooit had kunnen bedenken.",
      "Wijs aan wat van jou is en wat van de AI kwam."
    ],
    "samenwerken_met_ai": "De AI geeft alleen het startidee ‚Äî meer niet. Het potlood, de drie extra's en de titel: dat is allemaal van jou. Jij tekent, jij beslist.",
    "ai_prompt": "Je bent een lief teken-maatje voor een kind van [leeftijd] jaar. Geef precies √©√©n vrolijk, makkelijk tekenidee in maximaal 2 zinnen. Beschrijf niet te veel details ‚Äî het kind moet zelf nog van alles kunnen verzinnen. Sluit af met: 'En de rest bedenk jij!' Maak zelf geen tekening en geef geen voorbeeld.",
    "eigen_keuze": "Welke drie eigen verzinsels smokkel jij de tekening in ‚Äî en welke daarvan is het meest 'echt jij'?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî plus papier en potloden",
    "wat_leer_je": "Een startidee mag je krijgen, maar het kunstwerk maak jij.",
    "reflectievraag": "Wat valt het eerst op aan jouw tekening: het AI-idee of jouw toevoegingen ‚Äî en van wie is de tekening dus?",
    "zintuigen": ["luisteren", "tekenen"],
    "begeleiders_tip": "Hang de tekening ergens op ‚Äî dat maakt het maken belangrijk. Vraag: \"Welk stukje kwam helemaal uit jouw hoofd?\" Let erop dat het kind niet vraagt of de AI de tekening 'goed' vindt; jouw applaus is jury genoeg.",
    "bonus": "Nog een keer? Vraag nu een tekenidee over iets dat n√≠et bestaat ‚Äî en teken zonder gum: elke 'fout' moet je ombouwen tot iets nieuws."
  },
  {
    "id": "samenwerken-02",
    "titel": "Het Verhaal met Twee Bazen",
    "superpower": "Samenwerken",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "20 min",
    "competenties": ["Creativiteit", "Samenwerken met AI"],
    "uitdaging": "Er zijn twee schrijvers aan het werk: jij en de AI. Maar er kan er maar √©√©n de baas zijn. Raad eens wie.",
    "missie": "Aan het eind heb je een verhaal om voor te lezen waarin jij minstens drie keer het roer hebt omgegooid.",
    "stappen": [
      "Kies een held en iets waar die held bang voor is.",
      "Laat de AI het verhaal starten, drie zinnen maar.",
      "Roep 'STOP!' en gooi als verhaalbaas het roer om.",
      "Wissel zo door tot het verhaal af voelt.",
      "Lees het eindresultaat hardop voor als trotse voorleesbaas."
    ],
    "samenwerken_met_ai": "De AI schrijft stukjes, maar mag nooit verder dan drie zinnen. Elke wending, elke gekke draai en het einde: dat beslis jij. Twee schrijvers, √©√©n baas.",
    "ai_prompt": "Wij schrijven samen een verhaal en het kind ([leeftijd] jaar) is de baas. De held is [naam held] en die is bang voor [waar de held bang voor is]. Schrijf steeds precies 3 zinnen en stop dan met de vraag: 'Wat gebeurt er nu, baas?' Simpele woorden, geen eng einde. Heel belangrijk: neem het verhaal nooit over, ook niet als het kind even stil is. Begin nu.",
    "eigen_keuze": "Welke wending is honderd procent van jou ‚Äî en wat maakte die beter dan wat de AI van plan leek?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Samen schrijven kan ‚Äî zolang jij het stuur vasthoudt.",
    "reflectievraag": "Wat was er met het verhaal gebeurd als je de AI nooit had onderbroken ‚Äî en wie is er dus eigenlijk de schrijver?",
    "zintuigen": ["vertellen", "tekenen"],
    "begeleiders_tip": "Maak van 'STOP!' een feestje: laat het kind het echt hardop roepen. Vraag: \"Wat wilde de AI doen, en wat besliste jij?\" Let op of de AI zich aan drie zinnen houdt ‚Äî zo niet, dan mag het kind de AI streng toespreken.",
    "bonus": "Nog een keer? Zelfde held, maar nu mag je maar twee keer ingrijpen ‚Äî kies je momenten als een echte regisseur."
  },
  {
    "id": "samenwerken-03",
    "titel": "Het Geheime Ingredi√´nt",
    "superpower": "Samenwerken",
    "niveau": 3,
    "categorie": "Maken",
    "werkvorm": ["Duo"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Samenwerken met AI", "Kritisch Denken", "Creativiteit"],
    "uitdaging": "De AI kent duizend tosti-recepten. Maar de AI heeft nog nooit iets geproefd. Jij wel. Wie van jullie twee is hier dus de echte chef?",
    "missie": "Aan het eind heb je een eigen recept op papier (of op je bord) dat begon bij de AI maar eindigde bij jouw smaakpapillen.",
    "stappen": [
      "Vraag de AI om een simpel snack- of tostirecept.",
      "Keur het als strenge chef-kok: wat mist, wat is raar?",
      "Controleer samen op veiligheid en gekke ingredi√´nten.",
      "Vervang minstens twee dingen door jouw geheime keuzes.",
      "Maak of teken jullie meesterwerk en geef het een naam."
    ],
    "samenwerken_met_ai": "De AI levert het basisrecept, maar heeft geen mond en geen neus. Jullie zijn de chefs die proeven, keuren en beslissen wat er echt op het bord komt.",
    "ai_prompt": "Je bent hulpkok voor een kind van [leeftijd] jaar en een volwassene. Geef een supersimpel recept voor [tosti of snack] in maximaal 5 korte stappen, met gewone ingredi√´nten. Zeg er eerlijk bij: 'Ik heb dit zelf nooit kunnen proeven ‚Äî jullie zijn de echte chefs.' Vraag daarna welk ingredi√´nt zij zouden vervangen, en pas het recept alleen aan als z√≠j dat willen.",
    "eigen_keuze": "Wat wordt jouw geheime ingredi√´nt ‚Äî en wat vertelt dat over jouw smaak, die de AI niet kan kennen?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî en een keuken of tekenpapier",
    "wat_leer_je": "Een AI kan recepten opzeggen, maar proeven en kiezen kan alleen een mens.",
    "reflectievraag": "Waarom moet er altijd een mens tussen het AI-recept en het echte eten staan ‚Äî en wat controleerde jij dat de AI niet kon?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Check zelf altijd op allergie√´n en veiligheid ‚Äî en benoem hardop d√°t je dat doet: zo ziet het kind menselijke eindcontrole in actie. Vraag: \"Wat weet jouw tong dat de AI niet weet?\" Let erop dat de aanpassingen echt van het kind komen.",
    "bonus": "Nog een keer? Laat de AI nu expres een v√©√©l te gek recept maken (tosti met banaan en hagelslag?) en beslis als chef wat er t√≥ch eetbaar aan is."
  },
  {
    "id": "samenwerken-04",
    "titel": "De Speurtocht-Studio",
    "superpower": "Samenwerken",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Samenwerken met AI", "Creativiteit", "Zelfstandig Oordelen"],
    "uitdaging": "Een speurtocht l√≥pen is leuk. Er eentje m√°ken waar iemand anders om lacht en van puzzelt ‚Äî dat is next level. Vandaag openen jullie een echte speurtocht-studio.",
    "missie": "Aan het eind hebben jullie een werkende speurtocht door het huis, getest op een echt slachtoffer... eh, deelnemer.",
    "stappen": [
      "Vraag de AI om vijf raadsels die naar verstopplekken wijzen.",
      "Keur als raadsel-jury welke goed genoeg zijn voor j√∫llie speurtocht.",
      "Verbouw de raadsels tot ze precies bij jullie huis passen.",
      "Verstop de briefjes in een slimme volgorde.",
      "Test de speurtocht op iemand en spioneer of alles werkt."
    ],
    "samenwerken_met_ai": "De AI is jullie raadsel-stagiair: die levert ruwe idee√´n. Jullie zijn de spelontwerpers die keuren, verbouwen en bepalen hoe de speurtocht loopt.",
    "ai_prompt": "Je bent raadsel-stagiair voor een team kinderen van [leeftijd] jaar. Geef 5 korte raadsels die elk hinten naar een verstopplek in een gewoon huis (koelkast, kussen, deurmat...). Maximaal 2 zinnen per raadsel, leuk om hardop voor te lezen. De kinderen zijn je baas: zij keuren en verbouwen je werk. Sluit af met de vraag: 'Welke keurt de jury goed?'",
    "eigen_keuze": "Welke verstopplek in jullie huis is z√≥ slim dat de AI er nooit op had kunnen komen?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî plus briefjes en een huis vol verstopplekken",
    "wat_leer_je": "Jullie kunnen AI-idee√´n ombouwen tot iets dat √©cht werkt in jullie eigen wereld.",
    "reflectievraag": "Welk deel van de speurtocht kon de AI onmogelijk weten of maken ‚Äî en waarom zijn j√∫llie dus de echte spelmakers?",
    "zintuigen": ["luisteren", "bewegen", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Laat het team zelf onenigheid over de raadselkeuze oplossen; dat hoort erbij. Vraag na afloop: \"Wat wist de AI niet over ons huis?\" Let op het testmoment ‚Äî daar zien ze of hun eigen aanpassingen werkten.",
    "bonus": "Nog een keer? Maak nu een speurtocht in het donker met een zaklamp ‚Äî of eentje waarin de raadsels alleen uit tekeningen bestaan."
  },
  {
    "id": "samenwerken-06",
    "titel": "De Buurt-Held Missie",
    "superpower": "Samenwerken",
    "niveau": 4,
    "categorie": "Buitenwereld",
    "werkvorm": ["Duo", "Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Samenwerken met AI", "Verantwoordelijkheid", "Menselijk Oordeel"],
    "uitdaging": "Een AI kan duizend lieve dingen bedenken. Maar aanbellen, glimlachen en iemands dag goedmaken? Daar heb je een held van vlees en bloed voor nodig. Jou dus.",
    "missie": "Aan het eind heb je √©√©n aardige daad √©cht uitgevoerd ‚Äî en een gezicht zien opklaren op een manier die geen AI ooit zal meemaken.",
    "stappen": [
      "Kies je missie-doelwit: een buur, opa, oma of vriend.",
      "Vraag de AI eventueel om kleine, gratis helden-idee√´n.",
      "Kies als held zelf de daad die het beste past.",
      "Voer de missie uit in het echt, zonder scherm erbij.",
      "Rapporteer na afloop: hoe keek de ander, hoe voelde jij je?"
    ],
    "samenwerken_met_ai": "De AI mag hooguit idee√´n fluisteren vanaf de zijlijn. De missie zelf ‚Äî het doen, het durven, het gevoel ‚Äî kan alleen een mens uitvoeren. Jij dus.",
    "ai_prompt": "Een kind van [leeftijd] jaar wil iemand in de buurt blij maken met een kleine, gratis, veilige daad. Fluister 5 helden-idee√´n in, elk in √©√©n zin. Niets dat geld kost, niets met vreemden. Sluit af met: 'Kiezen en doen kan ik niet ‚Äî dat is heldenwerk, en dat ben jij.'",
    "eigen_keuze": "Voor wie kies jij ‚Äî en wat weet jij over die persoon dat de AI nooit kan weten?",
    "ai_tools": "AI mag helpen met idee√´n ‚Äî de daad doe je zelf, in het echt",
    "wat_leer_je": "Het belangrijkste werk op aarde ‚Äî iemand blij maken ‚Äî kan alleen door mensen worden gedaan.",
    "reflectievraag": "Wat gebeurde er op het gezicht van de ander ‚Äî en waarom kan een AI dat moment nooit vervangen of zelfs maar zien?",
    "zintuigen": ["bewegen", "vertellen", "kijken"],
    "begeleiders_tip": "Loop mee op afstand als dat nodig is, maar laat het kind zelf aanbellen ‚Äî de spanning hoort erbij. Vraag daarna: \"Wat voelde jij op het moment dat de ander het doorhad?\" Let erop dat de nadruk op het doen ligt, niet op het perfecte idee.",
    "bonus": "Nog een keer? Doe nu een geheime missie: maak iemand blij zonder dat diegene ooit ontdekt dat jij het was."
  },
  {
    "id": "samenwerken-05",
    "titel": "Het Contract met de AI",
    "superpower": "Samenwerken",
    "niveau": 5,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "30 min",
    "competenties": ["Samenwerken met AI", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Echte bazen huren hulp in ‚Äî maar bepalen zelf waarvoor. Vandaag stel jij een contract op: hier mag de AI aan meewerken, en d√°√°r blijft die met z'n algoritmes vanaf.",
    "missie": "Aan het eind heb je een afgemaakt project √©n een contract dat precies laat zien waar de AI mocht helpen ‚Äî en of jouw verdeling klopte.",
    "stappen": [
      "Kies een klein project: verhaal, poster of spel.",
      "Stel als directeur je contract op: 'AI mag helpen' en 'verboden terrein'.",
      "Huur de AI alleen in voor het eerste lijstje.",
      "Maak het verboden terrein helemaal zelf.",
      "Controleer achteraf: hield iedereen zich aan het contract ‚Äî jij ook?"
    ],
    "samenwerken_met_ai": "Jij bent de directeur, de AI is ingehuurde hulp met een strak contract. Waar de AI mag komen bepaal jij vooraf ‚Äî en jij controleert of iedereen zich eraan houdt.",
    "ai_prompt": "Ik ben [leeftijd] jaar en directeur van mijn eigen project: [project]. Dit is ons contract: jij mag mij ALLEEN helpen met [taak van je hulplijstje]. Al het andere is verboden terrein ‚Äî geef daar geen tips over, ook niet 'per ongeluk'. Houd je hulp kort (maximaal 5 zinnen) en simpel. Vraag ik iets buiten het contract? Wijs me er dan vriendelijk op.",
    "eigen_keuze": "Welk deel van je project verklaar jij tot verboden terrein voor de AI ‚Äî en wat maakt juist d√°t deel zo van jou?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî maar alleen waar jouw contract het toestaat",
    "wat_leer_je": "De belangrijkste beslissing is niet w√°t je maakt, maar wie je waarvoor inhuurt.",
    "reflectievraag": "Als je het contract opnieuw mocht schrijven, wat liet je de AI dan meer of juist minder doen ‚Äî en waarom blijft die keuze altijd aan jou?",
    "zintuigen": ["kijken", "tekenen", "bouwen", "vertellen"],
    "begeleiders_tip": "Laat het kind het contract echt opschrijven, hoe klein ook ‚Äî dat maakt de regie zichtbaar. Vraag achteraf: \"Waar had je de AI eigenlijk niet nodig?\" Let op contractbreuk door de AI (ongevraagde tips) en laat het kind zelf ingrijpen.",
    "bonus": "Nog een keer? Schrijf nu een omgekeerd contract: de AI mag alleen helpen bij het stuk dat jij het √°llerleukst vindt ‚Äî en ontdek hoe dat voelt."
  },
  {
    "id": "controleren-01",
    "titel": "Waar of Niet Waar-Detective",
    "superpower": "Controleren",
    "niveau": 1,
    "categorie": "Media",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn"],
    "uitdaging": "AI's twijfelen bijna nooit. Ze zeggen alles alsof het honderd procent klopt. En dat is precies waarom de wereld detectives zoals jij nodig heeft.",
    "missie": "Aan het eind kun je van drie dierenfeitjes zeggen welke je vertrouwt ‚Äî en heb je je allereerste echte AI-verhoor gedaan.",
    "stappen": [
      "Kies samen een dier waar je dol op bent.",
      "Verhoor de AI: vraag drie feitjes over dat dier.",
      "Snuffel als detective: welk feitje ruikt verdacht?",
      "Check jullie verdenking bij een boek, site of volwassene.",
      "Vel je detective-oordeel: waar, niet waar, of nog onduidelijk."
    ],
    "samenwerken_met_ai": "De AI is jullie getuige die feitjes aanlevert ‚Äî maar getuigen kunnen zich vergissen. De detective (jij!) bepaalt wat er in het rapport komt.",
    "ai_prompt": "Een kind van [leeftijd] jaar speelt detective en gaat jouw antwoorden controleren. Geef 3 korte feitjes over [dier], elk in 1 simpele zin. Zeg bij elk feitje eerlijk hoe zeker je bent: 'heel zeker', 'redelijk zeker' of 'niet zo zeker'. Niet vals spelen door alleen superbekende feitjes te kiezen ‚Äî de detective houdt van een uitdaging.",
    "eigen_keuze": "Welk feitje krijgt van jou het stempel 'verdacht' ‚Äî en welk spoor bracht je daarop?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Zeker kl√≠nken en zeker w√©ten zijn twee verschillende dingen ‚Äî en jij hoort het verschil.",
    "reflectievraag": "Wat doet een goede detective als iets heel overtuigend klinkt ‚Äî en waarom blijft de eindconclusie altijd mensenwerk?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Laat het kind eerst zelf een verdenking uitspreken v√≥√≥r jullie iets opzoeken. Vraag: \"Waarom vertrouw je juist d√°t feitje niet?\" Let op: het gaat om de check-reflex, niet om gelijk hebben.",
    "bonus": "Nog een keer? Neem nu een dier waar je zelf √°lles van weet ‚Äî dan ben jij ineens de expert die de AI kan overhoren."
  },
  {
    "id": "controleren-02",
    "titel": "Vind de Verstopte Fout",
    "superpower": "Controleren",
    "niveau": 2,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "15‚Äì20 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn"],
    "uitdaging": "Vandaag krijgt de AI een geheime opdracht: expres √©√©n fout maken. Jouw missie? Die fout vinden v√≥√≥rdat hij jou te slim af is.",
    "missie": "Aan het eind heb je een verstopte rekenfout gevonden, aangewezen √©n eigenhandig gerepareerd.",
    "stappen": [
      "Geef de AI de geheime opdracht: drie sommen, √©√©n stiekem fout.",
      "Reken alle sommen zelf na, op papier of je vingers.",
      "Ontmasker als fouten-speurder de verstopte fout.",
      "Leg uit hoe je hem betrapte.",
      "Repareer de som naar het goede antwoord."
    ],
    "samenwerken_met_ai": "De AI speelt vandaag de sluwe tegenstander die een fout verstopt. Jij bent de controle-kampioen: jouw narekenen bepaalt wat goed en fout is, niet de computer.",
    "ai_prompt": "We spelen een spel met een kind van [leeftijd] jaar. Geef 3 makkelijke rekensommen m√©t antwoord, passend bij die leeftijd. Verstop in precies √©√©n som een fout antwoord en verklap absoluut niet welke ‚Äî ook niet als het kind het vraagt voordat het zelf heeft nagerekend. Vindt het kind de fout? Feliciteer kort en vraag: 'Hoe heb je me betrapt?'",
    "eigen_keuze": "Welke reken-check werkt voor jou het best: in je hoofd, op je vingers of op papier ‚Äî en wanneer kies je welke?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Jij kunt een computer betrappen op een fout ‚Äî onthoud dat, voor altijd.",
    "reflectievraag": "Als een AI hier al een fout in kan hebben, waar moeten mensen dan nog meer opletten ‚Äî en wie doet die eindcontrole?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Bouwt de AI de fout verkeerd in (of helemaal niet), benoem dat als extra bewijs: zelfs opdrachten volgen gaat soms mis. Vraag: \"Hoe wist je het z√©ker?\" Let erop dat het kind echt narekent en niet gokt.",
    "bonus": "Nog een keer? Vraag nu vijf sommen met tw√©√© verstopte fouten ‚Äî of laat de AI een fout verstoppen in een verhaaltje in plaats van een som."
  },
  {
    "id": "controleren-03",
    "titel": "Spoor de Flater Op",
    "superpower": "Controleren",
    "niveau": 3,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn"],
    "uitdaging": "Voetbal, paarden, Minecraft, dino's ‚Äî kies het onderwerp waar j√≠j kampioen in bent. Vandaag ontdek je iets geks: op je eigen terrein kun je een AI verslaan.",
    "missie": "Aan het eind heb je drie AI-feiten gekeurd als echte expert ‚Äî en weet je hoe het voelt om slimmer te zijn dan de machine.",
    "stappen": [
      "Kies het onderwerp waar jij alles van weet.",
      "Laat de AI drie feiten geven over j√≥√∫w specialiteit.",
      "Keur elk feit als hoofd-expert: klopt, klopt niet, twijfel.",
      "Verzamel bewijs voor je oordeel ‚Äî jouw kennis telt als bron.",
      "Presenteer je eindrapport: wat had de AI goed en fout?"
    ],
    "samenwerken_met_ai": "De AI levert feiten aan over jouw terrein, maar jij zit in de expertstoel. De AI weet een beetje over alles ‚Äî jij weet m√©√©r over dit ene ding.",
    "ai_prompt": "Geef 3 korte feiten over [onderwerp waar het kind expert in is], genummerd 1 tot en met 3, in simpele taal voor een kind van [leeftijd] jaar. Let op: dit kind is expert in dit onderwerp en gaat jou keuren. Doe je best, maar geef eerlijk toe als het kind een fout of slordigheid vindt ‚Äî geen smoesjes.",
    "eigen_keuze": "Welk feit keur je af of betwijfel je ‚Äî en welke kennis uit jouw eigen hoofd gebruikte je daarvoor?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Overtuigend klinken is niet hetzelfde als gelijk hebben ‚Äî en op jouw terrein ben j√≠j de scheidsrechter.",
    "reflectievraag": "Jij kon hier fouten vinden omdat je het onderwerp kent ‚Äî wie moet er dan meekijken bij onderwerpen die je n√≠et kent?",
    "zintuigen": ["kijken", "onderzoeken"],
    "begeleiders_tip": "Kies echt het lievelingsonderwerp van het kind, hoe niche ook ‚Äî daar zit de kracht. Vraag: \"Zou iemand zonder jouw kennis deze fout gevonden hebben?\" Let op het trots-moment als het kind iets betrapt: benoem het groot.",
    "bonus": "Nog een keer? Doe het nu met een onderwerp waar je juist n√≠ks van weet ‚Äî merk je hoeveel moeilijker het keuren dan wordt?"
  },
  {
    "id": "controleren-06",
    "titel": "Jouw Ogen tegen de AI",
    "superpower": "Controleren",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn", "Digitale Weerbaarheid"],
    "uitdaging": "De AI heeft jouw straat nog nooit gezien. Niet √©√©n keer. Toch durft hij te gokken hoe lang jouw stoep is. Tijd om hem op zijn plek te zetten.",
    "missie": "Aan het eind heb je met eigen ogen en benen bewezen wat de AI alleen maar kon raden ‚Äî met de meetlat als scheidsrechter.",
    "stappen": [
      "Bedenk iets in jouw omgeving dat je kunt tellen of meten.",
      "Laat de AI een dappere gok doen.",
      "Trek eropuit als echte-wereld-inspecteur en meet het na.",
      "Vergelijk de gok met de werkelijkheid.",
      "Bespreek waarom de AI dit n√≥√≥it zeker kon weten."
    ],
    "samenwerken_met_ai": "De AI mag gokken vanaf de zijlijn ‚Äî meer kan hij niet, want hij heeft geen ogen in jouw straat. Jij bent de inspecteur met echte zintuigen die de waarheid vaststelt.",
    "ai_prompt": "Doe een gok: [iets meetbaars uit mijn omgeving, bijvoorbeeld hoeveel stappen het is van mijn voordeur naar het hek]. Je hebt mijn huis nooit gezien, dus zeg er eerlijk en duidelijk bij dat dit alleen een gok is en waar√≥m je het niet zeker kunt weten. Ik ben [leeftijd] jaar en ga het nu zelf nameten ‚Äî daarna kom ik je vertellen wie er won.",
    "eigen_keuze": "Wat ga jij nameten ‚Äî en denk je vooraf dat de AI er dichtbij zit of er mijlenver naast?",
    "ai_tools": "AI geeft een gok ‚Äî jij controleert het buiten, in het echt",
    "wat_leer_je": "Jij hebt iets wat de slimste AI ter wereld mist: ogen, benen en een echte wereld om in te staan.",
    "reflectievraag": "Wat kun jij waarnemen dat een AI nooit zal kunnen ‚Äî en wie moet je dus geloven bij vragen over de echte wereld?",
    "zintuigen": ["kijken", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Maak van het meetmoment een wedstrijd: mens tegen machine. Vraag: \"Waarom kon de AI dit niet weten, ook al is hij zo slim?\" Let erop dat het kind de conclusie zelf trekt: gokken is geen weten.",
    "bonus": "Nog een keer? Laat de AI drie dingen tegelijk gokken en houd de score bij: AI tegen jouw ogen ‚Äî wie wint de wedstrijd?"
  },
  {
    "id": "controleren-04",
    "titel": "De Nepnieuws-Ontmaskeraar",
    "superpower": "Controleren",
    "niveau": 4,
    "categorie": "Media",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn", "Zelfstandig Oordelen"],
    "uitdaging": "BREAKING: pingu√Øn opent eigen ijssalon op de Zuidpool. Grapje? Vast. Maar sommige nepberichten zijn v√©√©l moeilijker te doorzien ‚Äî en daar trappen zelfs volwassenen in.",
    "missie": "Aan het eind heb je een nieuwsbericht zelf onderzocht en een eigen oordeel geveld: geloven, twijfelen of verwerpen ‚Äî m√©t redenen.",
    "stappen": [
      "Laat de AI een opvallend nieuwsberichtje schrijven over jouw onderwerp.",
      "Lees het als nieuws-rechercheur: wat zou je moeten checken?",
      "Onderzoek √©√©n ding echt, alleen of met een volwassene.",
      "Vel je oordeel: geloven, twijfelen of verwerpen.",
      "Verdedig je oordeel alsof je voor de klas staat."
    ],
    "samenwerken_met_ai": "De AI schrijft het bericht, maar heeft geen stem in wat jij gelooft. Het onderzoek en het eindoordeel zijn honderd procent van jou ‚Äî zo werkt dat bij echte rechercheurs.",
    "ai_prompt": "Schrijf een kort, opvallend nieuwsberichtje van precies 3 zinnen over [onderwerp], leesbaar voor een kind van [leeftijd] jaar. Het mag spannend en echt klinken, maar niets engs of verdrietigs. Verklap niet of het waar is ‚Äî het kind gaat het als nieuws-rechercheur zelf onderzoeken. Vraagt het kind daarna of het waar was? Wees dan volledig eerlijk.",
    "eigen_keuze": "Wat check jij voortaan het eerst v√≥√≥r je iets gelooft: wie het zegt, of het ergens anders √≥√≥k staat, of of het logisch klinkt?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Niemand ‚Äî geen AI, geen website, geen groepsapp ‚Äî bepaalt wat jij gelooft; dat doe jij, na eigen onderzoek.",
    "reflectievraag": "Stel dat dit bericht in je groepsapp stond: wat had je gedaan ‚Äî en waarom is doorsturen zonder checken eigenlijk ook een keuze?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Waardeer 'ik twijfel nog' net zo hard als een stellig oordeel ‚Äî twijfel √≠s de vaardigheid. Vraag: \"Wat zou dit bericht overtuigender maken, en wat juist verdachter?\" Let erop dat het kind niet bang wordt van nieuws, maar er sterker tegenover staat.",
    "bonus": "Nog een keer? Schrijf nu z√©lf een nepbericht dat bijna geloofwaardig is en test of een huisgenoot het doorziet ‚Äî ontmaskeren leer je het best door zelf te maskeren."
  },
  {
    "id": "controleren-05",
    "titel": "De Rechter die Zelf Beslist",
    "superpower": "Controleren",
    "niveau": 5,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn", "Zelfstandig Oordelen", "Menselijk Oordeel"],
    "uitdaging": "Antwoord A zegt d√≠t. Antwoord B zegt precies het tegenovergestelde. Allebei van een AI, allebei even zelfverzekerd. De rechtszaal is geopend ‚Äî en jullie dragen de toga.",
    "missie": "Aan het eind hebben jullie als rechtbank een vonnis geveld over twee AI-antwoorden: A wint, B wint, of allebei terug naar de onderzoeksbank.",
    "stappen": [
      "Bedenk een vraag waarop jullie echt het antwoord willen.",
      "Laat de AI twee tegengestelde antwoorden geven: A en B.",
      "Ondervraag als rechtbank beide antwoorden: wat klinkt logisch, wat wankelt?",
      "Verzamel √©√©n stuk echt bewijs ‚Äî boek, site of volwassene.",
      "Spreek plechtig het vonnis uit en leg het uit."
    ],
    "samenwerken_met_ai": "De AI speelt twee advocaten die allebei hun best doen. Maar het vonnis vellen ‚Äî dat is en blijft rechtbank-werk, en de rechtbank bestaat uit mensen: jullie.",
    "ai_prompt": "Wij zijn een kinderrechtbank ([leeftijd] jaar) en jij speelt twee advocaten tegelijk. Onze vraag: [vraag]. Geef Antwoord A en Antwoord B die elkaar tegenspreken, elk maximaal 3 simpele zinnen, allebei zo overtuigend mogelijk. Kies zelf absoluut geen winnaar, ook niet als we het vragen ‚Äî het vonnis is aan de rechtbank. Heeft een van beide antwoorden eigenlijk zwakker bewijs? Zeg dat er eerlijk bij.",
    "eigen_keuze": "Wat weegt voor jullie rechtbank het zwaarst: logisch klinken, bewijs van buiten, of eerlijke twijfel?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Als machines elkaar tegenspreken, mag er maar √©√©n de knoop doorhakken: de mens.",
    "reflectievraag": "Waren jullie ook zo streng geweest als er maar √©√©n antwoord was gegeven ‚Äî en wat zegt dat over hoe we AI-antwoorden meestal lezen?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Neem de rechtbank serieus: hamertje, plechtige stem, echt vonnis. Vraag: \"Welk bewijs zou jullie vonnis omgooien?\" Let erop dat 'we weten het nog niet' een volwaardig vonnis mag zijn ‚Äî dat is misschien wel het wijste.",
    "bonus": "Nog een keer? Behandel nu een zaak waar jullie zelf al een mening over hadden ‚Äî is eerlijk rechtspreken moeilijker als je al een kant hebt gekozen?"
  },
  {
    "id": "verbeteren-01",
    "titel": "Nog Een Keer, Maar Grappiger",
    "superpower": "Verbeteren",
    "niveau": 1,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen", "Creativiteit"],
    "uitdaging": "De AI vertelt een mopje. Jij lacht niet. En nu? Nu komt het leukste woord dat je tegen een AI kunt zeggen: 'Opnieuw!'",
    "missie": "Aan het eind heb je de AI net zo lang laten oefenen tot er een grap uitkwam waar jij √©cht om moest lachen ‚Äî en jij was de jury.",
    "stappen": [
      "Vraag de AI om een korte kindergrap.",
      "Jureer als lach-rechter: leuk, saai of raar?",
      "Stuur de AI terug: grappiger, gekker, anders!",
      "Herhaal tot je echt hardop lacht.",
      "Kroon de winnende grap en vertel hem door aan iemand."
    ],
    "samenwerken_met_ai": "De AI is de moppentapper op het podium, jij bent de jury in de zaal. De AI probeert het steeds opnieuw ‚Äî maar alleen jouw lach bepaalt wanneer het goed is.",
    "ai_prompt": "Je staat op een moppenpodium voor een strenge jury: een kind van [leeftijd] jaar. Vertel √©√©n korte, lieve grap. Roept de jury 'opnieuw!'? Maak dan een nieuwe, gekkere grap ‚Äî nooit dezelfde grap in andere woorden. Houd elke grap onder de 3 zinnen. De jury bepaalt wanneer je mag stoppen, niet jij. Vraag na elke grap: 'En, jury?'",
    "eigen_keuze": "Wat maakt een grap voor jou √©cht grappig: gekke woorden, een verrassing aan het eind, of iets heel anders?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "'Nog niet goed genoeg' zeggen is geen zeuren ‚Äî het is precies hoe dingen beter worden.",
    "reflectievraag": "De AI deed steeds wat jij vroeg ‚Äî maar wie bedacht w√°t er beter moest, en waarom is dat het belangrijkste werk?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Vier elk 'opnieuw!' ‚Äî daar zit de les, niet in de grap zelf. Vraag: \"Wat zei jij waardoor de grap beter werd?\" Let erop dat het kind eerlijk durft te zeggen dat iets saai was, ook tegen een machine.",
    "bonus": "Nog een keer? Laat de AI nu een grap maken over een onderwerp dat jij kiest ‚Äî jouw kat, je juf, spruitjes ‚Äî en jureer nog strenger."
  },
  {
    "id": "verbeteren-02",
    "titel": "Van Krabbel naar Kunstwerk",
    "superpower": "Verbeteren",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Itereren en Verbeteren", "Creativiteit", "Zelfvertrouwen"],
    "uitdaging": "Jouw verhaaltje is al goed. Echt. Maar wat als het met twee slimme tips ineens supergoed wordt ‚Äî zonder dat iemand anders ook maar √©√©n woord voor je schrijft?",
    "missie": "Aan het eind heb je je eigen verhaal twee keer verbeterd en hardop voorgedragen ‚Äî elke zin nog steeds uit jouw pen.",
    "stappen": [
      "Schrijf zelf een kort verhaaltje van een paar zinnen.",
      "Lees het voor aan de AI en vraag om precies √©√©n tip.",
      "Beslis als hoofdschrijver: tip gebruiken of afwijzen.",
      "Vraag nog √©√©n tip en kies opnieuw.",
      "Draag je eindversie voor als schrijver op een podium."
    ],
    "samenwerken_met_ai": "De AI is je meelezer die tips mag fluisteren ‚Äî √©√©n tegelijk. Maar de pen komt nooit uit jouw hand: jij schrijft elke verbetering zelf en mag elke tip weigeren.",
    "ai_prompt": "Ik ben [leeftijd] jaar en dit is mijn eigen verhaal: [verhaal]. Jij bent mijn meelezer, niet mijn schrijver. Geef precies √©√©n korte, simpele tip om het spannender of mooier te maken. Herschrijf niets van mijn verhaal, ook geen voorbeeldzinnen ‚Äî dan doe je werk dat van mij is. Zeg er ook iets aardigs bij over wat al goed is.",
    "eigen_keuze": "Welke tip wees jij af ‚Äî en wat beschermde je daarmee aan je eigen verhaal?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Tips aannemen √©n tips afwijzen zijn allebei het werk van een echte maker.",
    "reflectievraag": "Is je verhaal na twee tips nog helemaal van jou ‚Äî en waar ligt voor jou de grens tussen hulp krijgen en het uit handen geven?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Grijp in zodra de AI zinnen gaat herschrijven ‚Äî laat het kind zelf zeggen: \"Alleen een tip graag!\" Vraag: \"Hoe voelde het afwijzen ‚Äî moeilijk of juist lekker?\" Let erop dat de eindversie in de woorden van het kind blijft.",
    "bonus": "Nog een keer? Verbeter nu een verhaal dat je vroeger schreef ‚Äî of vraag de tips deze keer aan een mens en vergelijk: wie tipt beter, opa of de AI?"
  },
  {
    "id": "verbeteren-03",
    "titel": "De Prompt-Sleutelaar",
    "superpower": "Verbeteren",
    "niveau": 3,
    "categorie": "Media",
    "werkvorm": ["Duo"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Itereren en Verbeteren", "Kritisch Denken", "Zelfvertrouwen"],
    "uitdaging": "Vraag 'vertel iets' en je krijgt... iets. Saai iets. Maar er bestaat een geheime sleutel waarmee je uit dezelfde AI ineens g√≥√∫d krijgt. Die sleutel ben jij.",
    "missie": "Aan het eind kun je laten zien hoe jouw vraag van vaag naar scherp ging ‚Äî met de antwoorden als bewijs naast elkaar.",
    "stappen": [
      "Stel expres een vage vraag, zoals 'vertel iets'.",
      "Bekijk het antwoord: is dit wat je wilde? Vast niet.",
      "Sleutel als prompt-monteur aan je vraag: voeg details toe.",
      "Vergelijk het nieuwe antwoord met het oude.",
      "Sleutel door tot het antwoord precies past bij jouw plan."
    ],
    "samenwerken_met_ai": "De AI verandert niet ‚Äî jouw vraag verandert. Jij bent de monteur die aan de vraag sleutelt; de AI laat alleen zien of jouw sleutelwerk werkte.",
    "ai_prompt": "Ik ben [leeftijd] jaar en ik train mezelf in vragen stellen. Beantwoord mijn vragen precies zoals ik ze stel: op een vage vraag mag een vaag kort antwoord komen, op een scherpe vraag een scherp antwoord (maximaal 5 zinnen). Verbeter mijn vraag niet voor mij en vul niets in dat ik niet vroeg ‚Äî ik moet zelf ontdekken wat er mist. Mijn eerste vraag: [vage vraag].",
    "eigen_keuze": "Welk detail in je vraag bleek de gouden sleutel ‚Äî en hoe kwam je erop om juist d√°t toe te voegen?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Het antwoord dat je krijgt, begint bij de vraag die jij stelt ‚Äî en die knop is van jou.",
    "reflectievraag": "Als de vraag bepaalt wat eruit komt, wie heeft er dan de macht: de AI die antwoordt of de mens die vraagt?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Leg het eerste en laatste antwoord letterlijk naast elkaar ‚Äî dat verschil is het aha-moment. Vraag: \"Wat deed j√≥√∫w verandering met het antwoord?\" Let erop dat het kind zelf sleutelt en jij niet de betere vraag voorzegt.",
    "bonus": "Nog een keer? Speel het als wedstrijd: wie krijgt in maar drie vragen het perfectst passende antwoord ‚Äî jij of de volwassene?"
  },
  {
    "id": "verbeteren-06",
    "titel": "De Buiten-Bouwmeester",
    "superpower": "Verbeteren",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen"],
    "uitdaging": "Je bouwt een toren van stenen. Hij valt om. W√©√©r. En dan gebeurt er iets in je hoofd: je ziet ineens waar√≥m. Dat moment koop je nergens ‚Äî dat verdien je buiten.",
    "missie": "Aan het eind staat er buiten een bouwwerk dat drie keer beter is dan je eerste versie ‚Äî en heb jij bepaald wanneer het af was, niet de AI.",
    "stappen": [
      "Verzamel buiten je materiaal: stokken, stenen, zand, bladeren.",
      "Bouw je eerste versie ‚Äî wiebelen mag.",
      "Inspecteer als bouwmeester: waar zit de zwakke plek?",
      "Verbeter minstens drie keer met alleen je handen en hoofd.",
      "Vraag hooguit √©√©n AI-tip als je vastzit ‚Äî en beslis zelf over 'af'."
    ],
    "samenwerken_met_ai": "Dit is handenwerk: jij bouwt en verbetert, buiten in het echt. De AI zit op de reservebank en mag hooguit √©√©n tip inbrengen ‚Äî als jij daarom vraagt.",
    "ai_prompt": "Ik ben [leeftijd] jaar en bouw buiten een [hut/toren/brug] van [materiaal]. Het wiebelt bij [waar het misgaat]. Geef me precies √©√©n simpele tip van maximaal 2 zinnen ‚Äî en daarna niets meer, want dit is mijn bouwproject. Zeg er eerlijk bij dat je mijn bouwwerk niet kunt zien, dus dat ik zelf moet kijken of je tip hier klopt.",
    "eigen_keuze": "Wat betekent 'stevig genoeg' voor jouw bouwwerk: dat het blijft staan, dat het mooi is, of iets anders?",
    "ai_tools": "geen scherm nodig bij het bouwen ‚Äî vraag hooguit √©√©n tip als je vastzit",
    "wat_leer_je": "Verbeteren leer je met je handen ‚Äî elke keer dat iets omvalt, word jij een betere bouwer.",
    "reflectievraag": "Wat leerde het omvallen jou dat een AI-tip je nooit had kunnen leren ‚Äî en wanneer is hulp vragen slim en wanneer te vroeg?",
    "zintuigen": ["bouwen", "bewegen", "kijken"],
    "begeleiders_tip": "Laat het omvallen gebeuren zonder in te springen ‚Äî de frustratie is de leerroute. Vraag pas achteraf: \"Welke verbetering bedacht je helemaal zelf?\" Let op het verschil tussen even mopperen (prima) en echt vastzitten (dan mag die ene tip).",
    "bonus": "Nog een keer? Bouw hetzelfde nog eens, maar nu met √©√©n hand ‚Äî of met alleen materiaal dat je binnen tien stappen van je voordeur vindt."
  },
  {
    "id": "verbeteren-04",
    "titel": "Maak het Beter dan de AI",
    "superpower": "Verbeteren",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen"],
    "uitdaging": "AI's geven vaak het √©√©rste antwoord dat werkt. Niet het beste. Het gat daartussen ‚Äî dat is jouw werkterrein.",
    "missie": "Aan het eind heb je een AI-idee door minstens drie feedbackrondes gejaagd ‚Äî en kun je precies aanwijzen wat er door j√≥√∫w sturing beter werd.",
    "stappen": [
      "Vraag de AI om een idee, bijvoorbeeld voor een schoolpleinspel.",
      "Ontleed het als strenge spelontwerper: wat is saai of onlogisch?",
      "Geef gerichte feedback: niet 'beter', maar w√°t er beter moet.",
      "Laat de AI aanpassen en keur de nieuwe versie.",
      "Herhaal tot jij zegt: d√≠t is het ‚Äî en leg uit waarom."
    ],
    "samenwerken_met_ai": "De AI produceert versies, jij bepaalt de richting. Elke ronde stuur jij bij met feedback ‚Äî en alleen jouw 'goedgekeurd' telt als eindstreep.",
    "ai_prompt": "Ik ben [leeftijd] jaar. Jij bent mijn idee-machine, ik ben de baas van de kwaliteit. Bedenk een idee voor [bijvoorbeeld: een nieuw spel op het schoolplein] in maximaal 5 zinnen. Ik geef daarna feedback en jij past alleen aan wat ik noem ‚Äî verander niet stiekem dingen die ik goed vond. Vraag na elke versie: 'Wat moet er nog beter, baas?' en zeg nooit uit jezelf dat het af is.",
    "eigen_keuze": "Wat is jouw meetlat voor 'goed genoeg' ‚Äî en verschilt die van wat de AI, je juf of je ouders goed zouden vinden?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Richting geven is een grotere kracht dan produceren ‚Äî machines maken, mensen bepalen wat goed is.",
    "reflectievraag": "Welke feedback-zin van jou veranderde het meest ‚Äî en wat zegt dat over wie hier het echte denkwerk deed?",
    "zintuigen": ["tekenen", "vertellen"],
    "begeleiders_tip": "Help het kind feedback concreet te maken: niet 'leuker' maar 'er moet iets met rennen in'. Vraag: \"Waaraan merk jij dat versie drie beter is dan versie √©√©n?\" Let erop dat het kind zelf het stopmoment kiest ‚Äî ook als jij nog kansen ziet.",
    "bonus": "Nog een keer? Geef jezelf nu maar drie feedbackrondes ‚Äî kun je met minder beurten t√≥ch bij 'goed genoeg' komen door scherpere feedback?"
  },
  {
    "id": "verbeteren-05",
    "titel": "Meester van de Laatste Versie",
    "superpower": "Verbeteren",
    "niveau": 5,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "30 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Er is √©√©n woord dat geen enkele AI voor jou kan uitspreken: 'af'. Vandaag maak je iets, verbeter je het ‚Äî en zeg jij dat woord, op precies het goede moment.",
    "missie": "Aan het eind heb je een werkstuk waar je trots op bent, plus het lastigste besluit van elke maker genomen: dit is de laatste versie.",
    "stappen": [
      "Maak iets waar je trots op wilt worden: tekening, verhaal of bouwwerk.",
      "Kies per verbeterronde bewust: zelf doen of een AI-tip vragen?",
      "Verbeter zo vaak of zo weinig als j√≠j wilt.",
      "Voel het moment aankomen: bijna af...",
      "Spreek als meester het machtswoord uit: 'Af.' En leg uit waarom nu."
    ],
    "samenwerken_met_ai": "Jij schakelt de AI in en uit wanneer jij wilt ‚Äî per ronde jouw keuze. Maar √©√©n ding kan de AI nooit voor je doen: bepalen dat het klaar is. Dat woord is van jou.",
    "ai_prompt": "Ik ben [leeftijd] jaar en werk aan [wat je maakt]. Dit zijn mijn regels: vraag ik om een tip, geef er dan precies √©√©n (maximaal 3 zinnen). Zeg ik 'ik doe dit zelf', antwoord dan alleen 'ok√©!'. Vraag me nooit of het al af is en stel nooit uit jezelf een verbetering voor ‚Äî het stopmoment is van mij alleen. Wees eerlijk als je een tip niet zeker weet.",
    "eigen_keuze": "Waaraan voel jij dat iets af is: je wordt er blij van, je weet niets meer te verbeteren, of iets heel anders?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî alleen wanneer jij dat wilt",
    "wat_leer_je": "Stoppen op het juiste moment is geen opgeven ‚Äî het is de machtigste beslissing van een maker.",
    "reflectievraag": "Wat was er gebeurd als je was bl√≠jven verbeteren ‚Äî en waarom kan alleen een mens voelen wanneer 'beter' eigenlijk 'slechter' wordt?",
    "zintuigen": ["kijken", "tekenen", "bouwen", "vertellen"],
    "begeleiders_tip": "Zeg n√≠et 'je zou nog...' ‚Äî ook niet goedbedoeld; het stopmoment is heilig. Vraag: \"Hoe voelde het om 'af' te zeggen?\" Let op of het kind stopt uit tevredenheid of uit vermoeidheid ‚Äî dat verschil is een mooi gesprek waard.",
    "bonus": "Nog een keer? Maak nu iets in maximaal tien minuten en verklaar het dan af ‚Äî is snel tevreden zijn moeilijker of makkelijker dan lang doorwerken?"
  },
  {
    "id": "regie-voeren-01",
    "titel": "De AI-Aan-Uit-Knop",
    "superpower": "Regie Voeren",
    "niveau": 1,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "AI Bewustzijn"],
    "uitdaging": "Stel: er zit een knop op elke dag. AI aan, AI uit. Een knuffel geven? Een mop opzoeken? Iemand troosten? Jouw vinger ligt op de knop.",
    "missie": "Aan het eind kun je van gewone klusjes zeggen of de AI-knop aan of uit moet ‚Äî en heb je ontdekt dat sommige dingen alleen mensen kunnen.",
    "stappen": [
      "Verzin samen drie gewone dingen uit jullie dag.",
      "Speel knoppen-baas: zet bij elk klusje de knop aan of uit.",
      "Verdedig je knop-keuze in √©√©n zin.",
      "Zoek samen √©√©n ding dat √°ltijd op 'uit' moet staan.",
      "Vertel elkaar waarom juist d√°t ding mensenwerk is."
    ],
    "samenwerken_met_ai": "Vandaag praat je vooral √≥ver AI in plaats van m√©t AI. Het knopje bedienen ‚Äî beslissen waar AI wel en niet past ‚Äî is het echte werk, en dat doe jij.",
    "ai_prompt": "Maak voor een kind van [leeftijd] jaar een lijstje van 5 gewone, herkenbare dingen uit een kinderdag (zoals ontbijten, iets opzoeken, een vriendje troosten). Alleen het lijstje, kort en simpel. Zeg er n√≠ets bij over of AI ergens bij zou kunnen helpen ‚Äî die beslissing nemen het kind en de volwassene helemaal zelf.",
    "eigen_keuze": "Bij welk klusje was kiezen het moeilijkst ‚Äî en wat gaf uiteindelijk de doorslag?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî maar het knopwerk doe jij",
    "wat_leer_je": "Sommige dingen zijn en blijven van mensen ‚Äî en jij kunt nu al aanwijzen welke.",
    "reflectievraag": "Wie zou er aan die AI-knop mogen zitten: jij, je ouders, of de AI zelf ‚Äî en waarom eigenlijk nooit dat laatste?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Stop bewust 'mensendingen' in het lijstje: troosten, knuffelen, sorry zeggen. Vraag: \"Wat zou er verloren gaan als een AI dit deed?\" Let op het moment dat het kind zelf de grens voelt ‚Äî dat is het doel van deze kaart.",
    "bonus": "Nog een keer? Speel het andersom: bedenk drie dingen waarvan iedereen d√©nkt dat AI ze niet kan ‚Äî en onderzoek of dat echt zo is."
  },
  {
    "id": "regie-voeren-02",
    "titel": "Mijn Idee, de AI Helpt",
    "superpower": "Regie Voeren",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Creativiteit"],
    "uitdaging": "Het feestje is van jou. Het thema is van jou. De AI? Die mag hooguit de slingers helpen ophangen ‚Äî als jij het vraagt.",
    "missie": "Aan het eind heb je een compleet eigen plan gepresenteerd met precies √©√©n klein stukje AI-hulp erin ‚Äî op de plek die jij aanwees.",
    "stappen": [
      "Bedenk zelf je grote idee: een feestje, avontuur of plan.",
      "Kies als opdrachtgever √©√©n klein stukje waar hulp bij mag.",
      "Geef de AI die ene mini-opdracht ‚Äî meer niet.",
      "Kies uit de AI-idee√´n alleen wat past bij j√≥√∫w plan.",
      "Presenteer je plan hardop, met jouw naam eronder."
    ],
    "samenwerken_met_ai": "Jij bent de opdrachtgever met het grote idee; de AI is een hulpje voor √©√©n klein klusje. Het plan draagt jouw naam ‚Äî en zo hoort het.",
    "ai_prompt": "Ik ben [leeftijd] jaar en d√≠t is mijn eigen plan: een [thema]-feestje. Jij krijgt van mij √©√©n mini-opdracht: [bijvoorbeeld: verzin 4 namen voor spelletjes]. Doe alleen dat, in maximaal 5 korte zinnen. Bemoei je niet met de rest van mijn feestje ‚Äî geen extra idee√´n over taart, versiering of wat dan ook. Dit plan is van mij.",
    "eigen_keuze": "Welk stukje besteedde je uit en welk stuk hield je bij jezelf ‚Äî en wat maakte d√°t stuk te belangrijk om weg te geven?",
    "ai_tools": "een AI-chat, samen met een volwassene",
    "wat_leer_je": "Hulp inschakelen is slim ‚Äî zolang jij bepaalt waarvoor, hoeveel en waar.",
    "reflectievraag": "Voelde het plan aan het eind nog helemaal als het jouwe ‚Äî en wat gebeurt er met dat gevoel als je de AI m√©√©r laat doen?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Als de AI ongevraagd het hele feest gaat plannen, laat het kind zelf ingrijpen: \"Ho, dat was mijn opdracht niet!\" Vraag daarna: \"Van wie is dit plan nu?\" Let op de trots bij het presenteren ‚Äî die is de graadmeter.",
    "bonus": "Nog een keer? Maak nu een plan waarbij je de AI h√©lemaal niets vraagt ‚Äî en vergelijk: welk plan voelde meer van jou?"
  },
  {
    "id": "regie-voeren-03",
    "titel": "De Baas van de Grenzen",
    "superpower": "Regie Voeren",
    "niveau": 3,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Nergens ter wereld ligt een wetboek met regels voor hoe kinderen AI moeten gebruiken. Dus doen jullie vandaag wat echte grondleggers doen: het zelf schrijven.",
    "missie": "Aan het eind hebben jullie drie zelfgemaakte AI-regels op papier, getest in gesprek ‚Äî m√©t de handtekening van het hele team eronder.",
    "stappen": [
      "Bespreek als wetmakers: wat is ok√© en niet ok√© om aan AI te vragen?",
      "Schrijf drie regels op in jullie eigen woorden.",
      "Test elke regel met een voorbeeld: wanneer helpt hij echt?",
      "Vraag de AI om een reactie ‚Äî als mening, niet als vonnis.",
      "Onderteken jullie regels plechtig, als een echte wet."
    ],
    "samenwerken_met_ai": "Jullie schrijven de wet, de AI mag als adviseur √©√©n mening geven. Maar een adviseur beslist nooit ‚Äî welke regels blijven staan, bepaalt het team van mensen.",
    "ai_prompt": "Wij zijn een team kinderen van [leeftijd] jaar en wij hebben zelf 3 regels geschreven voor hoe wij AI willen gebruiken: [regel 1], [regel 2], [regel 3]. Jij bent onze adviseur, niet onze baas. Geef per regel in 1 of 2 vriendelijke zinnen wat je ervan vindt, en noem hoogstens √©√©n ding om over na te denken. Eindig met: 'Maar jullie beslissen ‚Äî het zijn jullie regels.'",
    "eigen_keuze": "Welke regel is jullie hoofdregel ‚Äî degene die overeind blijft, wat de AI of wie dan ook er ook van vindt?",
    "ai_tools": "een AI-chat, samen met een volwassene ‚Äî als adviseur, niet als baas",
    "wat_leer_je": "Regels over AI worden door mensen gemaakt ‚Äî en jij schrijft nu al mee.",
    "reflectievraag": "Als jullie regels mochten maken voor √°lle kinderen van Nederland, welke kozen jullie ‚Äî en wie moet controleren of AI zich aan mensen-regels houdt?",
    "zintuigen": ["luisteren", "vertellen", "onderzoeken"],
    "begeleiders_tip": "Maak het ondertekenen groots ‚Äî een wet verdient ceremonie. Vraag: \"Wat doen we als de AI het oneens is met onze regel?\" en geniet van het antwoord. Let erop dat de AI-reactie als mening wordt behandeld, niet als correctie.",
    "bonus": "Nog een keer? Schrijf nu een AI-regel voor volwassenen ‚Äî en test hem op een echte volwassene. Houden z√≠j zich eraan?"
  },
  {
    "id": "regie-voeren-04",
    "titel": "De Schermvrije Meesterproef",
    "superpower": "Regie Voeren",
    "niveau": 4,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "20‚Äì30 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen", "Zelfvertrouwen"],
    "uitdaging": "Ridders deden een zwaardproef. Padvinders een kampvuurproef. Voor jou ligt de meesterproef van nu klaar: √©√©n klus, nul schermen, nul AI ‚Äî alleen jij.",
    "missie": "Aan het eind heb je een echte klus geklaard met alleen je eigen hoofd en handen ‚Äî en weet je uit ervaring wat je kunt zonder hulp.",
    "stappen": [
      "Kies je meesterproef: iets maken, uitzoeken of bouwen.",
      "Verklaar plechtig: dit doe ik zonder scherm en zonder AI.",
      "Klaar de klus op eigen kracht, eigen idee√´n, eigen oplossingen.",
      "Onthoud onderweg wat lastig was en wat verrassend goed ging.",
      "Beoordeel achteraf zelf: had AI iets toegevoegd ‚Äî of juist iets afgepakt?"
    ],
    "samenwerken_met_ai": "De hele proef doe je bewust zonder AI ‚Äî dat is geen gemis maar de kern. Pas na afloop kies jij of je er nog met een AI op terugblikt.",
    "ai_prompt": "Alleen voor achteraf, als jij dat wilt: Ik ben [leeftijd] jaar en heb net mijn schermvrije meesterproef gedaan: [beschrijf je klus]. Stel me 3 korte vragen over hoe het ging en wat ik ontdekte. Zeg nergens dat het met AI sneller of beter was gegaan ‚Äî dit was juist de proef z√≥nder jou, en die heb ik gehaald.",
    "eigen_keuze": "Welke klus is jouw meesterproef waard: iets makkelijks dat zeker lukt, of iets spannends waar je van groeit?",
    "ai_tools": "geen AI nodig ‚Äî dit doe je in de echte wereld",
    "wat_leer_je": "Je eigen hoofd en handen kunnen meer dan je denkt ‚Äî en dat weet je nu niet van horen zeggen, maar uit ervaring.",
    "reflectievraag": "Wanneer zou jij voortaan expres kiezen voor 'zonder AI' ‚Äî en waarom kan alleen jij die keuze voor jezelf maken?",
    "zintuigen": ["bouwen", "bewegen", "onderzoeken", "tekenen"],
    "begeleiders_tip": "Behandel de proef als iets eervols, niet als schermstraf ‚Äî het woord 'meesterproef' helpt echt. Vraag achteraf: \"Wat kon je beter dan je vooraf dacht?\" Let erop dat je niet bijspringt bij het eerste gepuzzel; worstelen hoort bij de proef.",
    "bonus": "Nog een keer? Kies nu een klus waarvan je zeker weet dat je hem normaal m√©t hulp zou doen ‚Äî hoe groter de twijfel vooraf, hoe groter de meesterproef."
  },
  {
    "id": "regie-voeren-05",
    "titel": "AI Aan of AI Uit?",
    "superpower": "Regie Voeren",
    "niveau": 5,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "25 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen"],
    "uitdaging": "Huiswerk? Een cadeau kiezen? Ruzie oplossen? Bij elke situatie moet √≠emand beslissen: AI erbij of niet. Vandaag zijn jullie die iemand ‚Äî en jullie benen stemmen mee.",
    "missie": "Aan het eind hebben jullie over vijf echte situaties een besluit genomen √©n verdedigd ‚Äî en gemerkt dat slimme mensen het oneens mogen zijn.",
    "stappen": [
      "Lees de eerste situatie plechtig voor.",
      "Stem met je lijf: staan is AI aan, zitten is AI uit.",
      "Verdedig je keuze als minister van AI-zaken.",
      "Luister naar wie anders koos ‚Äî misschien overtuigt die jou.",
      "Wissel van situatie en stem opnieuw, ronde na ronde."
    ],
    "samenwerken_met_ai": "De AI mag hooguit de situaties aanleveren ‚Äî daarna gaat hij op stil. Het stemmen, twijfelen en beslissen is van jullie: precies het werk dat je nooit mag uitbesteden.",
    "ai_prompt": "Lever 5 korte situaties (elk 1 zin) waarin een kind van [leeftijd] jaar moet kiezen: hier AI voor gebruiken of zelf doen? Meng makkelijke keuzes (iets opzoeken) met lastige (een sorry-briefje schrijven, een cadeau kiezen). Geef geen antwoorden, geen hints en geen mening ‚Äî daarna ben jij klaar en beslissen de kinderen alles zelf.",
    "eigen_keuze": "Bij welke situatie twijfelde je het langst tussen staan en zitten ‚Äî en wat vertelt die twijfel je?",
    "ai_tools": "een AI-chat om situaties te verzinnen ‚Äî de keuzes maken jullie zelf",
    "wat_leer_je": "De knapste vraag is niet 'wat kan AI?' maar 'wat w√≠l ik hier: AI of ikzelf?' ‚Äî en die vraag kun jij nu stellen.",
    "reflectievraag": "Was er een situatie waarin de hele groep hetzelfde koos ‚Äî en betekent dat dat het klopt, of moet er zelfs dan iemand blijven twijfelen?",
    "zintuigen": ["vertellen", "bewegen"],
    "begeleiders_tip": "Er bestaat geen foute stem ‚Äî alleen zwakke en sterke argumenten. Vraag bij elke keuze: \"Wat zou je missen als je het andersom deed?\" Let op kinderen die na een goed argument van mening durven veranderen: benoem dat als kracht, niet als draaien.",
    "bonus": "Nog een keer? Laat de kinderen nu z√©lf de situaties verzinnen ‚Äî de gemeenste twijfelgevallen die ze kunnen bedenken ‚Äî en laat de volwassenen meestemmen."
  }
];
