/*
 * AI Explorer Academy ‚Äî cards-en.js
 * English edition of the Explorer Card library (29 cards, editorial version).
 * Core philosophy in every card: AI is the starting point, not the end point ‚Äî the child stays in charge.
 * Fixed fields (id, superpower, niveau, categorie, werkvorm, competenties, zintuigen, tijdsduur)
 * are identical to the Dutch source; all free-text fields are written natively in English
 * (localized, not literally translated). New field: bonus.
 * Order: Ontdekken ‚Üí Samenwerken ‚Üí Controleren ‚Üí Verbeteren ‚Üí Regie Voeren, by rising level.
 */
window.CARDS_EN = [
  {
    "id": "ontdekken-01",
    "titel": "The Why Machine",
    "superpower": "Ontdekken",
    "niveau": 1,
    "categorie": "Onderzoek",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Nieuwsgierigheid", "AI Bewustzijn"],
    "uitdaging": "Why is the sky blue? Why is tape sticky? Somewhere in your head lives a question nobody has ever answered for you. Today, you set it free.",
    "missie": "By the end, you'll have an answer to your weirdest why-question ever ‚Äî and you'll have decided for yourself whether you believe it.",
    "stappen": [
      "Think up three why-questions you're genuinely curious about.",
      "Pick the weirdest one as your champion question.",
      "Ask it to the AI together with a grown-up.",
      "Play scientist: ask the AI how sure it really is.",
      "Decide for yourself: do I believe this, or do I want to know more?"
    ],
    "samenwerken_met_ai": "The AI is your answer helper: it gives you a starting point. But you are the question-asker AND the judge ‚Äî you decide whether the answer is good enough.",
    "ai_prompt": "You are a cheerful explainer for a child aged [age]. The child has a why-question: [your why-question]. Answer in no more than 4 short, simple sentences. Say honestly how sure you are: very sure, a bit sure, or actually nobody knows. Then ask one curious question back, so the child keeps thinking for themselves. Do not take over the thinking.",
    "eigen_keuze": "Which of your three questions wins the title 'weirdest question ever' ‚Äî and why that one?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "You're allowed to ask ANYTHING ‚Äî and you decide for yourself whether to believe the answer.",
    "reflectievraag": "What do you do when the AI says 'I'm not sure about that' ‚Äî and who gets to decide what you believe then?",
    "zintuigen": ["vertellen", "luisteren"],
    "begeleiders_tip": "Have the child guess out loud BEFORE the AI answers. Ask: \"What do you think the answer is?\" Watch that the child doesn't just nod along with the AI's answer ‚Äî doubt is a win here.",
    "bonus": "Do it again? This time ask a why-question about yourself (why do I have to yawn when someone else yawns?) ‚Äî and see if the AI dares to be just as sure about YOU."
  },
  {
    "id": "ontdekken-02",
    "titel": "The Animal Mix-Up Machine",
    "superpower": "Ontdekken",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15‚Äì20 min",
    "competenties": ["Nieuwsgierigheid", "Creativiteit"],
    "uitdaging": "Deep in the jungle lives a beast with spikes AND wings. Nobody has ever seen it. Makes sense ‚Äî it only starts existing when you invent it today.",
    "missie": "By the end, you'll have a drawing of a brand-new animal that never existed anywhere ‚Äî with a name, a superpower and its very own sound.",
    "stappen": [
      "Pick two animals that would never appear in the same photo.",
      "Ask the AI to mix them into one brand-new creature.",
      "Play animal inventor: change at least one thing about the AI's idea.",
      "Draw the animal exactly the way YOU see it in your head.",
      "Invent your animal's sound and act it out loud."
    ],
    "samenwerken_met_ai": "The AI is your idea factory and tosses out a starter animal. You are the inventor who decides how the animal REALLY looks, sounds and is called.",
    "ai_prompt": "Pretend you are a wacky animal factory for a child aged [age]. Mix a [animal 1] with a [animal 2] into one new animal. Give it a funny name and tell what it can do in no more than 4 short, cheerful sentences. Then ask what the child wants to change about the animal ‚Äî and describe nothing more until the child has answered. The animal belongs to the child, not to you.",
    "eigen_keuze": "What will you change about the AI's animal: the head, the color, the superpower ‚Äî and why exactly that?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî plus paper and markers",
    "wat_leer_je": "AI can spark ideas, but only your imagination makes the animal real.",
    "reflectievraag": "Whose animal is this really: yours or the AI's ‚Äî and where can you see that in your drawing?",
    "zintuigen": ["luisteren", "tekenen", "vertellen"],
    "begeleiders_tip": "Let the child sketch first, BEFORE you read out the AI's description. Ask: \"What did you come up with that the AI didn't see?\" Watch that the child doesn't start copying the AI's version ‚Äî the difference is the gold.",
    "bonus": "Do it again? Mix three animals at once this time ‚Äî or let someone at home pick the two animals, so you're stuck with an impossible combination."
  },
  {
    "id": "ontdekken-03",
    "titel": "Hunt for the Fake Word",
    "superpower": "Ontdekken",
    "niveau": 3,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Nieuwsgierigheid", "Kritisch Denken"],
    "uitdaging": "Some words are so strange they sound made up. And sometimes the AI sneaks in one it really did make up. Who's fooling who here?",
    "missie": "By the end, you'll have a list of proven-real words, at least one suspicion you chased down ‚Äî and one brand-new word of your own.",
    "stappen": [
      "Ask the AI for three super-strange real words and what they mean.",
      "Play word detective: point at the word that feels most fake.",
      "Look up every word in a real dictionary.",
      "Cross out anything that was wrong and crown what turned out real.",
      "Invent one new word yourself that really SHOULD exist."
    ],
    "samenwerken_met_ai": "The AI delivers the words; you're the detective with the dictionary. It's not the AI but YOUR checking that decides what counts as real.",
    "ai_prompt": "You are helping a child aged [age] who is playing word detective. Give 3 very strange but real English words with their meanings, each with a funny example sentence. Keep each explanation under 2 sentences, simple and friendly. Not sure whether one of the words really exists? Say so honestly ‚Äî the child is going to check up on you anyway.",
    "eigen_keuze": "Which word do you suspect the most ‚Äî and what gives it away: the sound, the meaning, or your gut feeling?",
    "ai_tools": "an AI chat plus a real dictionary (paper or online)",
    "wat_leer_je": "Checking isn't a chore, it's a treasure hunt ‚Äî and you're good at it.",
    "reflectievraag": "How did it feel to check the AI instead of just believing it ‚Äî and who had the last word in the end?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "AI sometimes invents words or meanings for real. Celebrate loudly when that happens: \"You caught an AI!\" Ask: \"What made this word smell fishy to you?\" Make sure the child handles the dictionary themselves.",
    "bonus": "Do it again? Flip it around: invent two fake words and pick one real one, then test whether the grown-up ‚Äî or the AI! ‚Äî can spot the fake."
  },
  {
    "id": "ontdekken-06",
    "titel": "The Sound Hunter",
    "superpower": "Ontdekken",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo", "Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Nieuwsgierigheid", "AI Bewustzijn"],
    "uitdaging": "Shhh. Close your eyes. Count the sounds around you. Three? Four? A real sound hunter finds ten ‚Äî without a single screen.",
    "missie": "By the end, you'll have ten captured sounds on your hunting list ‚Äî and you'll know which sound no computer could ever copy.",
    "stappen": [
      "Sneak outside or to an open window; screens stay indoors.",
      "Hunt like a sound spy for ten different sounds.",
      "Draw or write down every catch on your hunting list.",
      "Pick the sound a computer could never, ever copy.",
      "Only afterwards ‚Äî if you want to ‚Äî talk over your catch with the AI."
    ],
    "samenwerken_met_ai": "During the hunt, the AI stays home: your ears do all the work. Only afterwards may the AI join the conversation about your catch ‚Äî as a chat-later buddy, not as a hunter.",
    "ai_prompt": "I am [age] years old and I just captured these sounds outside, without a screen: [your list]. You are my chat-later buddy. Pick the sound from my list that a computer would find hardest to copy and explain why in no more than 3 simple sentences. Be honest if you're not sure. Then ask me which sound I liked best ‚Äî my ears were there, yours weren't.",
    "eigen_keuze": "Which sound from your list would you save if it were the very last sound on Earth?",
    "ai_tools": "no AI needed ‚Äî you do this with your own ears in the real world (chatting about it afterwards is allowed)",
    "wat_leer_je": "Your ears pick up things no computer in the world can sense.",
    "reflectievraag": "What did you hear that an AI never could have ‚Äî and what does that tell you about who should go exploring: you or the computer?",
    "zintuigen": ["luisteren", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Start with one minute of total silence together ‚Äî for kids that's already an adventure. Ask: \"Which sound did you hear for the very first time just now?\" Make sure the screen only comes out AFTER the hunt.",
    "bonus": "Do it again? Hunt in the dark this time, or hunt for the ten QUIETEST sounds you can find ‚Äî those are the hardest to catch."
  },
  {
    "id": "ontdekken-04",
    "titel": "Captain of the Idea Storm",
    "superpower": "Ontdekken",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Nieuwsgierigheid", "Creativiteit", "Zelfstandig Oordelen"],
    "uitdaging": "Getting ten ideas is easy. Throwing nine of them overboard ‚Äî THAT'S captain's work. Do you dare to choose?",
    "missie": "By the end, you'll have actually built one idea you chose yourself with stuff from around the house ‚Äî and scrapped nine ideas with total conviction.",
    "stappen": [
      "Ask the AI for ten building ideas using stuff from around the house.",
      "Cross out nine ideas like a captain ‚Äî no regrets.",
      "Pick the idea that makes YOU itch to start, not the 'best' one.",
      "Build it and change anything you like better along the way.",
      "Inspect your creation: what turned out cooler than planned?"
    ],
    "samenwerken_met_ai": "The AI is your idea storm: it blows in ten directions at once. You are the captain who sets the course ‚Äî the AI gets no say in which idea wins.",
    "ai_prompt": "A child aged [age] is looking for building inspiration. Give exactly 10 numbered craft or building ideas using ordinary things from around the house, each in one short sentence. Do not pick a favorite and do not say which idea is best ‚Äî the child is the captain who chooses. After that, your job is done: no extra tips unless the child asks.",
    "eigen_keuze": "Which idea did you pick ‚Äî and which 'more sensible' idea did it beat?",
    "ai_tools": "an AI chat for the ideas ‚Äî the building you do yourself",
    "wat_leer_je": "Choosing is a superpower: daring to say 'this one ‚Äî and none of the rest' out of ten ideas.",
    "reflectievraag": "Which was harder: getting ideas or throwing ideas away ‚Äî and who's better at the throwing-away part, you or the AI?",
    "zintuigen": ["kijken", "bouwen", "onderzoeken"],
    "begeleiders_tip": "Don't steer toward the 'best' idea ‚Äî not even with your eyebrows. Ask: \"Which idea keeps nagging at you?\" Watch whether the child chooses with their heart ‚Äî that's exactly the point.",
    "bonus": "Do it again? Ask the AI for ten deliberately TERRIBLE ideas this time ‚Äî and turn the very worst one into something good anyway."
  },
  {
    "id": "ontdekken-05",
    "titel": "Expedition Unplugged",
    "superpower": "Ontdekken",
    "niveau": 5,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "20‚Äì30 min",
    "competenties": ["Nieuwsgierigheid", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "The great explorers had no AI. Neither did your great-grandma. Yet they discovered more than most people with a phone. Today you test their secret.",
    "missie": "By the end, you'll have made three real discoveries using only your own senses ‚Äî and decided for yourself whether AI gets to add anything afterwards.",
    "stappen": [
      "Put every screen away and declare yourself expedition leader.",
      "Scout indoors or outdoors for three things you always walk right past.",
      "Study them like an explorer: up close and for a long time.",
      "Draw or memorize what you'd never noticed before.",
      "Only then decide: may AI add anything, or was this complete?"
    ],
    "samenwerken_met_ai": "On this expedition you deliberately travel without AI ‚Äî that's the whole art of it. Afterwards, YOU are the one who decides whether the AI even gets to speak.",
    "ai_prompt": "Only for afterwards, if you choose: I am [age] years old and I just discovered this on my own, without a screen: [your three discoveries]. Do not give me explanations and do not give me answers. Only ask me 3 short, curious questions that make me look even more closely. My discovery stays mine.",
    "eigen_keuze": "Will you ask the AI anything afterwards, or keep this discovery entirely to yourself ‚Äî and why?",
    "ai_tools": "no AI needed ‚Äî you do this in the real world",
    "wat_leer_je": "The best discovery machine in existence is already inside your head.",
    "reflectievraag": "When does AI make a discovery bigger, and when does it make it smaller ‚Äî and who should decide that, every single time?",
    "zintuigen": ["kijken", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Join in with screens away yourself ‚Äî kids instantly sense when this isn't fair. Ask: \"What did you only see once you kept looking?\" Watch the final moment: the 'AI in or out' choice must TRULY belong to the child.",
    "bonus": "Do it again? Run the expedition somewhere you find 'boring' ‚Äî the hallway, the shed, the parking lot. Boring doesn't exist for real explorers."
  },
  {
    "id": "samenwerken-01",
    "titel": "The Drawing Buddy",
    "superpower": "Samenwerken",
    "niveau": 1,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Samenwerken met AI", "Creativiteit"],
    "uitdaging": "Blank paper. Pencil ready. And then... nothing. Everyone knows that empty-page feeling. But from today, you have a buddy who always has a starter idea.",
    "missie": "By the end, you'll have a drawing that started with an AI idea ‚Äî but is packed with things only you could have dreamed up.",
    "stappen": [
      "Ask your drawing buddy (the AI) for one funny drawing idea.",
      "Draw the starter idea as well as you can.",
      "Become a secret decorating agent: smuggle in three ideas of your own.",
      "Invent a title the AI never could have thought of.",
      "Point out what's yours and what came from the AI."
    ],
    "samenwerken_met_ai": "The AI only gives the starter idea ‚Äî nothing more. The pencil, the three extras and the title: those are all yours. You draw, you decide.",
    "ai_prompt": "You are a kind drawing buddy for a child aged [age]. Give exactly one cheerful, easy drawing idea in no more than 2 sentences. Don't describe too many details ‚Äî the child needs room to invent plenty of their own. End with: 'And the rest is up to you!' Do not make a drawing yourself and do not give an example.",
    "eigen_keuze": "Which three inventions of your own will you smuggle into the drawing ‚Äî and which one is the most 'totally you'?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî plus paper and pencils",
    "wat_leer_je": "A starter idea can be a gift ‚Äî but the artwork is made by you.",
    "reflectievraag": "What do you notice first in your drawing: the AI's idea or your additions ‚Äî so whose drawing is it, really?",
    "zintuigen": ["luisteren", "tekenen"],
    "begeleiders_tip": "Hang the drawing up somewhere ‚Äî that makes the making matter. Ask: \"Which part came entirely out of your head?\" Watch that the child doesn't ask whether the AI 'likes' the drawing; your applause is jury enough.",
    "bonus": "Do it again? Ask for a drawing idea about something that does NOT exist ‚Äî and draw without an eraser: every 'mistake' has to become something new."
  },
  {
    "id": "samenwerken-02",
    "titel": "The Story with Two Bosses",
    "superpower": "Samenwerken",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "20 min",
    "competenties": ["Creativiteit", "Samenwerken met AI"],
    "uitdaging": "Two writers are on the job: you and the AI. But only one of you can be the boss. Guess who.",
    "missie": "By the end, you'll have a story ready to read aloud in which you grabbed the wheel and changed course at least three times.",
    "stappen": [
      "Pick a hero and something that hero is afraid of.",
      "Let the AI start the story ‚Äî three sentences, no more.",
      "Shout 'STOP!' and spin the story your way, like the story boss you are.",
      "Keep taking turns until the story feels finished.",
      "Read the final result out loud as the proud reading-aloud boss."
    ],
    "samenwerken_met_ai": "The AI writes little pieces, but never more than three sentences at a time. Every twist, every crazy turn and the ending: you decide. Two writers, one boss.",
    "ai_prompt": "We are writing a story together and the child ([age] years old) is the boss. The hero is [hero's name] and they are afraid of [what the hero fears]. Always write exactly 3 sentences, then stop and ask: 'What happens next, boss?' Simple words, no scary ending. Very important: never take over the story, not even when the child goes quiet for a moment. Start now.",
    "eigen_keuze": "Which twist is one hundred percent yours ‚Äî and what made it better than whatever the AI seemed to be planning?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Writing together works ‚Äî as long as you keep your hands on the wheel.",
    "reflectievraag": "What would have happened to the story if you'd never interrupted the AI ‚Äî so who is the real writer here?",
    "zintuigen": ["vertellen", "tekenen"],
    "begeleiders_tip": "Turn 'STOP!' into a celebration: have the child really shout it out loud. Ask: \"What was the AI about to do, and what did YOU decide?\" Check whether the AI sticks to three sentences ‚Äî if not, the child gets to tell it off, firmly.",
    "bonus": "Do it again? Same hero, but this time you're only allowed to step in twice ‚Äî pick your moments like a real director."
  },
  {
    "id": "samenwerken-03",
    "titel": "The Secret Ingredient",
    "superpower": "Samenwerken",
    "niveau": 3,
    "categorie": "Maken",
    "werkvorm": ["Duo"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Samenwerken met AI", "Kritisch Denken", "Creativiteit"],
    "uitdaging": "The AI knows a thousand grilled cheese recipes. But the AI has never tasted anything. Not once. You have. So which of you two is the real chef here?",
    "missie": "By the end, you'll have your own recipe on paper (or on your plate) that started with the AI but ended with your taste buds.",
    "stappen": [
      "Ask the AI for a simple snack or grilled cheese recipe.",
      "Judge it like a strict head chef: what's missing, what's weird?",
      "Check it together for safety and strange ingredients.",
      "Swap at least two things for your own secret choices.",
      "Make or draw your masterpiece and give it a name."
    ],
    "samenwerken_met_ai": "The AI supplies the base recipe, but it has no mouth and no nose. You two are the chefs who taste, judge and decide what actually lands on the plate.",
    "ai_prompt": "You are the kitchen assistant for a child aged [age] and a grown-up. Give a super-simple recipe for [grilled cheese or a snack] in no more than 5 short steps, using ordinary ingredients. Add honestly: 'I have never been able to taste this myself ‚Äî you two are the real chefs.' Then ask which ingredient they would swap, and only change the recipe if THEY want you to.",
    "eigen_keuze": "What will your secret ingredient be ‚Äî and what does it say about your taste, which the AI can never know?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî and a kitchen or drawing paper",
    "wat_leer_je": "An AI can recite recipes, but tasting and choosing ‚Äî only a human can do that.",
    "reflectievraag": "Why does a human always have to stand between the AI's recipe and the actual food ‚Äî and what did you check that the AI couldn't?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Always check for allergies and safety yourself ‚Äî and say out loud THAT you're doing it: that's how the child sees human final-checking in action. Ask: \"What does your tongue know that the AI doesn't?\" Make sure the changes truly come from the child.",
    "bonus": "Do it again? Ask the AI for a deliberately ridiculous recipe this time (grilled cheese with banana and marshmallows?) and decide, as the chef, what's actually worth eating."
  },
  {
    "id": "samenwerken-04",
    "titel": "The Treasure Hunt Studio",
    "superpower": "Samenwerken",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Samenwerken met AI", "Creativiteit", "Zelfstandig Oordelen"],
    "uitdaging": "Doing a treasure hunt is fun. MAKING one that gets someone else laughing and puzzling ‚Äî that's next level. Today you're opening a real treasure hunt studio.",
    "missie": "By the end, you'll have a working treasure hunt through the house, tested on a real victim... er, participant.",
    "stappen": [
      "Ask the AI for five riddles that point to hiding spots.",
      "Judge them as the riddle jury: which are good enough for YOUR hunt?",
      "Rebuild the riddles until they fit your house exactly.",
      "Hide the clue notes in a clever order.",
      "Test the hunt on someone and spy to see if everything works."
    ],
    "samenwerken_met_ai": "The AI is your riddle intern: it delivers rough ideas. You are the game designers who judge, rebuild and decide how the hunt flows.",
    "ai_prompt": "You are the riddle intern for a team of kids aged [age]. Give 5 short riddles that each hint at a hiding spot in an ordinary house (fridge, pillow, doormat...). No more than 2 sentences per riddle, fun to read aloud. The kids are your boss: they judge and rebuild your work. End with the question: 'Which ones does the jury approve?'",
    "eigen_keuze": "Which hiding spot in your house is so clever the AI never could have thought of it?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî plus notes and a house full of hiding spots",
    "wat_leer_je": "You can rebuild AI ideas into something that REALLY works in your own world.",
    "reflectievraag": "Which part of the hunt was impossible for the AI to know or make ‚Äî and why does that make YOU the real game makers?",
    "zintuigen": ["luisteren", "bewegen", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Let the team settle their own disagreements about which riddles win; that's part of it. Ask afterwards: \"What didn't the AI know about our house?\" Watch the test moment ‚Äî that's where they see whether their own changes worked.",
    "bonus": "Do it again? Make a treasure hunt in the dark with a flashlight ‚Äî or one where the riddles are drawings only, no words allowed."
  },
  {
    "id": "samenwerken-06",
    "titel": "The Neighborhood Hero Mission",
    "superpower": "Samenwerken",
    "niveau": 4,
    "categorie": "Buitenwereld",
    "werkvorm": ["Duo", "Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Samenwerken met AI", "Verantwoordelijkheid", "Menselijk Oordeel"],
    "uitdaging": "An AI can think up a thousand kind things. But ringing a doorbell, smiling, and making someone's day? That takes a flesh-and-blood hero. That's you.",
    "missie": "By the end, you'll have actually done one kind deed ‚Äî and watched a face light up in a way no AI will ever get to see.",
    "stappen": [
      "Pick your mission target: a neighbor, grandpa, grandma or friend.",
      "Ask the AI for small, free hero ideas if you want to.",
      "Choose the deed that fits best ‚Äî you're the hero, you pick.",
      "Carry out the mission for real, no screen in sight.",
      "Report back afterwards: how did they look, how did you feel?"
    ],
    "samenwerken_met_ai": "The AI may whisper ideas from the sidelines, at most. The mission itself ‚Äî the doing, the daring, the feeling ‚Äî only a human can pull off. You, that is.",
    "ai_prompt": "A child aged [age] wants to make someone in the neighborhood happy with a small, free, safe act of kindness. Whisper 5 hero ideas, each in one sentence. Nothing that costs money, nothing involving strangers. End with: 'Choosing and doing is not something I can do ‚Äî that's hero work, and the hero is you.'",
    "eigen_keuze": "Who do you choose ‚Äî and what do you know about that person that the AI could never know?",
    "ai_tools": "AI may help with ideas ‚Äî the deed you do yourself, in real life",
    "wat_leer_je": "The most important work on Earth ‚Äî making someone happy ‚Äî can only be done by humans.",
    "reflectievraag": "What happened on the other person's face ‚Äî and why can an AI never replace that moment, or even see it?",
    "zintuigen": ["bewegen", "vertellen", "kijken"],
    "begeleiders_tip": "Walk along at a distance if needed, but let the child ring the doorbell themselves ‚Äî the nerves are part of it. Ask afterwards: \"What did you feel the moment they realized?\" Keep the focus on the doing, not on finding the perfect idea.",
    "bonus": "Do it again? Run a secret mission this time: make someone happy without them ever finding out it was you."
  },
  {
    "id": "samenwerken-05",
    "titel": "The AI Contract",
    "superpower": "Samenwerken",
    "niveau": 5,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "30 min",
    "competenties": ["Samenwerken met AI", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Real bosses hire help ‚Äî but decide exactly what for. Today you draw up a contract: HERE the AI may pitch in, and THERE it keeps its algorithms to itself.",
    "missie": "By the end, you'll have a finished project AND a contract that shows exactly where the AI was allowed to help ‚Äî and whether your split was right.",
    "stappen": [
      "Pick a small project: a story, poster or game.",
      "As the director, write your contract: 'AI may help with' and 'off-limits'.",
      "Hire the AI for the first list only.",
      "Make the off-limits part entirely by yourself.",
      "Check afterwards: did everyone stick to the contract ‚Äî including you?"
    ],
    "samenwerken_met_ai": "You are the director; the AI is hired help on a strict contract. You decide in advance where the AI is allowed ‚Äî and you check that everyone sticks to it.",
    "ai_prompt": "I am [age] years old and the director of my own project: [project]. This is our contract: you may ONLY help me with [task from your help list]. Everything else is off-limits ‚Äî give no tips about it, not even 'by accident'. Keep your help short (no more than 5 sentences) and simple. If I ask for something outside the contract, kindly point it out to me.",
    "eigen_keuze": "Which part of your project do you declare off-limits to the AI ‚Äî and what makes exactly that part so yours?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî but only where your contract allows it",
    "wat_leer_je": "The most important decision isn't WHAT you make, but who you hire for which job.",
    "reflectievraag": "If you could rewrite the contract, what would you let the AI do more of ‚Äî or less ‚Äî and why does that choice always stay yours?",
    "zintuigen": ["kijken", "tekenen", "bouwen", "vertellen"],
    "begeleiders_tip": "Have the child actually write the contract down, however small ‚Äî that makes being in charge visible. Ask afterwards: \"Where did you not really need the AI at all?\" Watch for contract breaches by the AI (unasked-for tips) and let the child step in themselves.",
    "bonus": "Do it again? Write a reversed contract this time: the AI may only help with the part you enjoy the MOST ‚Äî and find out how that feels."
  },
  {
    "id": "controleren-01",
    "titel": "True or False Detective",
    "superpower": "Controleren",
    "niveau": 1,
    "categorie": "Media",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn"],
    "uitdaging": "AIs almost never hesitate. They say everything as if it's one hundred percent true. And that's exactly why the world needs detectives like you.",
    "missie": "By the end, you'll be able to say which of three animal facts you trust ‚Äî and you'll have done your very first real AI interrogation.",
    "stappen": [
      "Pick an animal you love, together.",
      "Interrogate the AI: ask for three facts about that animal.",
      "Sniff around like a detective: which fact smells suspicious?",
      "Check your suspicion against a book, a website or a grown-up.",
      "Deliver your detective verdict: true, false, or still unclear."
    ],
    "samenwerken_met_ai": "The AI is your witness delivering the facts ‚Äî but witnesses can be mistaken. The detective (you!) decides what goes in the report.",
    "ai_prompt": "A child aged [age] is playing detective and will check your answers. Give 3 short facts about [animal], each in 1 simple sentence. For each fact, say honestly how sure you are: 'very sure', 'fairly sure' or 'not so sure'. No cheating by only picking super-famous facts ‚Äî this detective likes a challenge.",
    "eigen_keuze": "Which fact gets your 'suspicious' stamp ‚Äî and what clue put you on its trail?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Sounding sure and being sure are two different things ‚Äî and you can hear the difference.",
    "reflectievraag": "What does a good detective do when something sounds really convincing ‚Äî and why is the final verdict always a job for humans?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Have the child voice a suspicion BEFORE you look anything up. Ask: \"Why don't you trust that particular fact?\" Remember: it's about the checking reflex, not about being right.",
    "bonus": "Do it again? Pick an animal you know EVERYTHING about ‚Äî suddenly you're the expert who gets to quiz the AI."
  },
  {
    "id": "controleren-02",
    "titel": "Find the Hidden Mistake",
    "superpower": "Controleren",
    "niveau": 2,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "15‚Äì20 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn"],
    "uitdaging": "Today the AI gets a secret assignment: make one mistake on purpose. Your mission? Find that mistake before it outsmarts you.",
    "missie": "By the end, you'll have found a hidden math mistake, pointed it out AND fixed it with your own hands.",
    "stappen": [
      "Give the AI its secret assignment: three sums, one sneaky mistake.",
      "Recheck every sum yourself, on paper or on your fingers.",
      "Unmask the hidden mistake like a true error hunter.",
      "Explain how you caught it.",
      "Repair the sum with the correct answer."
    ],
    "samenwerken_met_ai": "Today the AI plays the sly opponent hiding a mistake. You are the checking champion: your own math decides what's right and wrong ‚Äî not the computer.",
    "ai_prompt": "We are playing a game with a child aged [age]. Give 3 easy math sums WITH answers, suited to that age. Hide a wrong answer in exactly one sum and absolutely do not reveal which one ‚Äî not even if the child asks before they've checked the sums themselves. When the child finds the mistake, congratulate them briefly and ask: 'How did you catch me?'",
    "eigen_keuze": "Which checking method works best for you: in your head, on your fingers or on paper ‚Äî and when do you pick which?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "You can catch a computer making a mistake ‚Äî remember that, forever.",
    "reflectievraag": "If an AI can slip up even here, where else should people stay alert ‚Äî and who does that final check?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "If the AI hides the mistake wrong (or not at all), name that as extra evidence: even following instructions can go wrong. Ask: \"How did you know for SURE?\" Make sure the child really recalculates instead of guessing.",
    "bonus": "Do it again? Ask for five sums with TWO hidden mistakes ‚Äî or have the AI hide a mistake in a little story instead of a sum."
  },
  {
    "id": "controleren-03",
    "titel": "Spot the Slip-Up",
    "superpower": "Controleren",
    "niveau": 3,
    "categorie": "Onderzoek",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn"],
    "uitdaging": "Soccer, horses, Minecraft, dinosaurs ‚Äî pick the subject where YOU are the champion. Today you'll discover something strange: on your home turf, you can beat an AI.",
    "missie": "By the end, you'll have judged three AI facts as a true expert ‚Äî and you'll know what it feels like to be smarter than the machine.",
    "stappen": [
      "Pick the subject you know everything about.",
      "Have the AI give three facts about YOUR specialty.",
      "Judge each fact as head expert: correct, wrong, or doubtful.",
      "Gather evidence for your verdict ‚Äî your own knowledge counts as a source.",
      "Present your final report: what did the AI get right and wrong?"
    ],
    "samenwerken_met_ai": "The AI delivers facts about your turf, but you're in the expert's chair. The AI knows a little about everything ‚Äî you know MORE about this one thing.",
    "ai_prompt": "Give 3 short facts about [subject the child is an expert in], numbered 1 to 3, in simple language for a child aged [age]. Careful: this child is an expert on this subject and is going to grade you. Do your best, but admit it honestly if the child finds a mistake or something sloppy ‚Äî no excuses.",
    "eigen_keuze": "Which fact do you reject or doubt ‚Äî and what knowledge from your own head did you use to do it?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Sounding convincing is not the same as being right ‚Äî and on your turf, YOU are the referee.",
    "reflectievraag": "You could find mistakes here because you know the subject ‚Äî so who should double-check when it's a subject you DON'T know?",
    "zintuigen": ["kijken", "onderzoeken"],
    "begeleiders_tip": "Pick the child's genuine favorite subject, however niche ‚Äî that's where the power is. Ask: \"Would someone without your knowledge have caught this mistake?\" Watch for the proud moment when the child catches something: make it big.",
    "bonus": "Do it again? Try it with a subject you know NOTHING about ‚Äî notice how much harder the judging suddenly gets?"
  },
  {
    "id": "controleren-06",
    "titel": "Your Eyes vs. the AI",
    "superpower": "Controleren",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn", "Digitale Weerbaarheid"],
    "uitdaging": "The AI has never seen your street. Not once. Yet it dares to guess how long your sidewalk is. Time to put it in its place.",
    "missie": "By the end, you'll have proven with your own eyes and legs what the AI could only guess ‚Äî with the measuring tape as referee.",
    "stappen": [
      "Think of something in your surroundings you can count or measure.",
      "Have the AI take a brave guess.",
      "Head out as a real-world inspector and measure it for real.",
      "Compare the guess with reality.",
      "Talk about why the AI could NEVER know this for sure."
    ],
    "samenwerken_met_ai": "The AI may guess from the sidelines ‚Äî that's all it can do, because it has no eyes on your street. You are the inspector with real senses who establishes the truth.",
    "ai_prompt": "Take a guess: [something measurable near me, for example how many steps it is from my front door to the gate]. You have never seen my home, so say clearly and honestly that this is only a guess and WHY you can't know it for sure. I am [age] years old and I'm going to measure it myself right now ‚Äî then I'll come back and tell you who won.",
    "eigen_keuze": "What will you measure ‚Äî and do you predict the AI will land close, or miss by a mile?",
    "ai_tools": "AI takes a guess ‚Äî you check it outside, for real",
    "wat_leer_je": "You have something the smartest AI in the world is missing: eyes, legs and a real world to stand in.",
    "reflectievraag": "What can you observe that an AI never will ‚Äî so who should you trust with questions about the real world?",
    "zintuigen": ["kijken", "bewegen", "onderzoeken"],
    "begeleiders_tip": "Turn the measuring moment into a match: human versus machine. Ask: \"Why couldn't the AI know this, even though it's so smart?\" Make sure the child draws the conclusion themselves: guessing is not knowing.",
    "bonus": "Do it again? Have the AI guess three things at once and keep score: AI versus your eyes ‚Äî who wins the match?"
  },
  {
    "id": "controleren-04",
    "titel": "The Fake News Buster",
    "superpower": "Controleren",
    "niveau": 4,
    "categorie": "Media",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Kritisch Denken", "Digitale Weerbaarheid", "AI Bewustzijn", "Zelfstandig Oordelen"],
    "uitdaging": "BREAKING: penguin opens its own ice cream shop at the South Pole. A joke? Probably. But some fake stories are MUCH harder to see through ‚Äî and even grown-ups fall for those.",
    "missie": "By the end, you'll have investigated a news story yourself and reached your own verdict: believe it, doubt it, or reject it ‚Äî with reasons.",
    "stappen": [
      "Have the AI write an eye-catching little news story about your topic.",
      "Read it like a news investigator: what would need checking?",
      "Really investigate one thing, alone or with a grown-up.",
      "Reach your verdict: believe, doubt, or reject.",
      "Defend your verdict as if you're standing in front of the class."
    ],
    "samenwerken_met_ai": "The AI writes the story, but gets no vote in what you believe. The investigation and the final verdict are one hundred percent yours ‚Äî that's how real investigators work.",
    "ai_prompt": "Write a short, eye-catching news item of exactly 3 sentences about [topic], readable for a child aged [age]. It may sound exciting and real, but nothing scary or sad. Do not reveal whether it's true ‚Äî the child is going to investigate it as a news detective. If the child asks afterwards whether it was true, be completely honest.",
    "eigen_keuze": "What will you check first from now on before believing something: who says it, whether it appears somewhere else too, or whether it sounds logical?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Nobody ‚Äî no AI, no website, no group chat ‚Äî decides what you believe; you do, after your own investigation.",
    "reflectievraag": "Imagine this story popped up in your group chat: what would you have done ‚Äî and why is forwarding without checking also a choice?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Value 'I'm still not sure' just as highly as a firm verdict ‚Äî doubt IS the skill. Ask: \"What would make this story more convincing, and what would make it more suspicious?\" Make sure the child doesn't end up afraid of news, but stronger in front of it.",
    "bonus": "Do it again? Now write a nearly-believable fake story YOURSELF and test whether someone at home sees through it ‚Äî the best way to learn unmasking is to do the masking."
  },
  {
    "id": "controleren-05",
    "titel": "You Be the Judge",
    "superpower": "Controleren",
    "niveau": 5,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "25‚Äì30 min",
    "competenties": ["Kritisch Denken", "AI Bewustzijn", "Zelfstandig Oordelen", "Menselijk Oordeel"],
    "uitdaging": "Answer A says THIS. Answer B says the exact opposite. Both from an AI, both equally confident. The court is now in session ‚Äî and you're wearing the robes.",
    "missie": "By the end, your court will have delivered a verdict on two AI answers: A wins, B wins, or both go back for more investigation.",
    "stappen": [
      "Think of a question you genuinely want answered.",
      "Have the AI give two opposing answers: A and B.",
      "Cross-examine both answers as a court: what sounds logical, what wobbles?",
      "Gather one piece of real evidence ‚Äî a book, a website or a grown-up.",
      "Solemnly pronounce the verdict and explain it."
    ],
    "samenwerken_met_ai": "The AI plays two lawyers, both doing their very best. But delivering the verdict ‚Äî that is and stays courtroom work, and the court is made of humans: you.",
    "ai_prompt": "We are a children's court ([age] years old) and you are playing two lawyers at once. Our question: [question]. Give Answer A and Answer B that contradict each other, each in no more than 3 simple sentences, both as convincing as you can make them. Absolutely do not pick a winner yourself, even if we ask ‚Äî the verdict belongs to the court. If one of the answers actually has weaker evidence, say so honestly.",
    "eigen_keuze": "What weighs most in your court: sounding logical, outside evidence, or honest doubt?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "When machines contradict each other, only one party gets to break the tie: the human.",
    "reflectievraag": "Would you have been this strict if there had been only ONE answer ‚Äî and what does that say about how we usually read AI answers?",
    "zintuigen": ["luisteren", "onderzoeken", "vertellen"],
    "begeleiders_tip": "Take the court seriously: little gavel, solemn voice, real verdict. Ask: \"What evidence would flip your verdict?\" Remember that 'we don't know yet' counts as a full verdict ‚Äî maybe the wisest one of all.",
    "bonus": "Do it again? Try a case where you already had an opinion ‚Äî is judging fairly harder when you've already picked a side?"
  },
  {
    "id": "verbeteren-01",
    "titel": "Again, But Funnier",
    "superpower": "Verbeteren",
    "niveau": 1,
    "categorie": "Verbeelding",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen", "Creativiteit"],
    "uitdaging": "The AI tells a joke. You don't laugh. Now what? Now comes the most fun word you can say to an AI: 'Again!'",
    "missie": "By the end, you'll have made the AI practice until out came a joke that REALLY made you laugh ‚Äî and you were the judge the whole time.",
    "stappen": [
      "Ask the AI for a short kids' joke.",
      "Judge it as the laughter judge: funny, boring or weird?",
      "Send the AI back: funnier, sillier, different!",
      "Repeat until you truly laugh out loud.",
      "Crown the winning joke and pass it on to somebody."
    ],
    "samenwerken_met_ai": "The AI is the comedian on stage; you're the judge in the audience. The AI keeps trying ‚Äî but only YOUR laugh decides when it's good.",
    "ai_prompt": "You are on a comedy stage in front of a strict judge: a child aged [age]. Tell one short, sweet joke. If the judge shouts 'again!', make a new, sillier joke ‚Äî never the same joke in different words. Keep every joke under 3 sentences. The judge decides when you may stop, not you. After every joke, ask: 'Well, judge?'",
    "eigen_keuze": "What makes a joke REALLY funny to you: silly words, a surprise at the end, or something else entirely?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Saying 'not good enough yet' isn't whining ‚Äî it's exactly how things get better.",
    "reflectievraag": "The AI kept doing what you asked ‚Äî but who decided WHAT needed to be better, and why is that the most important job?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Celebrate every 'again!' ‚Äî that's where the lesson lives, not in the joke itself. Ask: \"What did YOU say that made the joke better?\" Watch that the child dares to say something was boring ‚Äî even to a machine.",
    "bonus": "Do it again? Have the AI make a joke about a topic you pick ‚Äî your cat, your teacher, broccoli ‚Äî and judge even more strictly."
  },
  {
    "id": "verbeteren-02",
    "titel": "From Scribble to Masterpiece",
    "superpower": "Verbeteren",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Itereren en Verbeteren", "Creativiteit", "Zelfvertrouwen"],
    "uitdaging": "Your little story is already good. Really. But what if two smart tips could make it AMAZING ‚Äî without anyone else writing a single word for you?",
    "missie": "By the end, you'll have improved your own story twice and performed it out loud ‚Äî every sentence still from your own pen.",
    "stappen": [
      "Write a short story of a few sentences, all by yourself.",
      "Read it to the AI and ask for exactly one tip.",
      "Decide as head writer: use the tip or turn it down.",
      "Ask for one more tip and choose again.",
      "Perform your final version like a writer on stage."
    ],
    "samenwerken_met_ai": "The AI is your reading buddy who may whisper tips ‚Äî one at a time. But the pen never leaves your hand: you write every improvement yourself and may refuse any tip.",
    "ai_prompt": "I am [age] years old and this is my own story: [story]. You are my reading buddy, not my writer. Give exactly one short, simple tip to make it more exciting or more beautiful. Do not rewrite any of my story, not even example sentences ‚Äî that would be doing work that belongs to me. Also say something kind about what's already good.",
    "eigen_keuze": "Which tip did you turn down ‚Äî and what part of your own story were you protecting?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Taking tips AND turning tips down are both the work of a real maker.",
    "reflectievraag": "After two tips, is your story still completely yours ‚Äî and where is the line for you between getting help and handing it over?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Step in the moment the AI starts rewriting sentences ‚Äî let the child say it themselves: \"Just a tip, please!\" Ask: \"How did turning a tip down feel ‚Äî hard, or actually great?\" Make sure the final version stays in the child's own words.",
    "bonus": "Do it again? Improve a story you wrote ages ago ‚Äî or ask a human for the tips this time and compare: who gives better tips, Grandpa or the AI?"
  },
  {
    "id": "verbeteren-03",
    "titel": "The Prompt Mechanic",
    "superpower": "Verbeteren",
    "niveau": 3,
    "categorie": "Media",
    "werkvorm": ["Duo"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Itereren en Verbeteren", "Kritisch Denken", "Zelfvertrouwen"],
    "uitdaging": "Ask 'tell me something' and you get... something. Boring something. But there's a secret key that suddenly gets GOLD out of the very same AI. That key is you.",
    "missie": "By the end, you'll be able to show how your question went from vague to sharp ‚Äî with the answers lined up side by side as proof.",
    "stappen": [
      "Ask a deliberately vague question, like 'tell me something'.",
      "Look at the answer: is this what you wanted? Doubt it.",
      "Tinker with your question like a prompt mechanic: add details.",
      "Compare the new answer with the old one.",
      "Keep tinkering until the answer fits your plan exactly."
    ],
    "samenwerken_met_ai": "The AI doesn't change ‚Äî your question does. You're the mechanic tinkering with the question; the AI only shows whether your tinkering worked.",
    "ai_prompt": "I am [age] years old and I'm training myself to ask better questions. Answer my questions exactly as I ask them: a vague question may get a vague short answer, a sharp question gets a sharp answer (no more than 5 sentences). Do not improve my question for me and do not fill in anything I didn't ask ‚Äî I need to discover what's missing myself. My first question: [vague question].",
    "eigen_keuze": "Which detail in your question turned out to be the golden key ‚Äî and how did you think of adding exactly that?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "The answer you get starts with the question you ask ‚Äî and that dial belongs to you.",
    "reflectievraag": "If the question decides what comes out, who holds the power: the AI that answers or the human who asks?",
    "zintuigen": ["luisteren", "onderzoeken"],
    "begeleiders_tip": "Put the first and last answers literally side by side ‚Äî that difference is the aha moment. Ask: \"What did YOUR change do to the answer?\" Make sure the child does the tinkering and you don't whisper the better question.",
    "bonus": "Do it again? Play it as a contest: who gets the perfectly fitting answer in only three questions ‚Äî you or the grown-up?"
  },
  {
    "id": "verbeteren-06",
    "titel": "The Outdoor Master Builder",
    "superpower": "Verbeteren",
    "niveau": 3,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen"],
    "uitdaging": "You build a tower of stones. It falls over. AGAIN. And then something happens in your head: suddenly you see WHY. You can't buy that moment anywhere ‚Äî you earn it outside.",
    "missie": "By the end, there'll be a structure standing outside that's three times better than your first version ‚Äî and YOU decided when it was finished, not the AI.",
    "stappen": [
      "Gather your materials outside: sticks, stones, sand, leaves.",
      "Build your first version ‚Äî wobbling allowed.",
      "Inspect it like a master builder: where's the weak spot?",
      "Improve it at least three times using only your hands and head.",
      "Ask at most one AI tip if you're stuck ‚Äî and decide 'finished' yourself."
    ],
    "samenwerken_met_ai": "This is hands-on work: you build and improve, outside, for real. The AI sits on the bench and may offer one tip at most ‚Äî if you ask for it.",
    "ai_prompt": "I am [age] years old and I'm building a [den/tower/bridge] outside out of [material]. It wobbles at [where it goes wrong]. Give me exactly one simple tip of no more than 2 sentences ‚Äî and then nothing more, because this is my building project. Also say honestly that you can't see my structure, so I have to look for myself whether your tip fits here.",
    "eigen_keuze": "What does 'strong enough' mean for your structure: that it stays standing, that it looks great, or something else?",
    "ai_tools": "no screen needed while building ‚Äî ask at most one tip if you're stuck",
    "wat_leer_je": "You learn improving with your hands ‚Äî every time something falls over, you become a better builder.",
    "reflectievraag": "What did the falling-over teach you that an AI tip never could ‚Äî and when is asking for help smart, and when is it too soon?",
    "zintuigen": ["bouwen", "bewegen", "kijken"],
    "begeleiders_tip": "Let the collapse happen without jumping in ‚Äî the frustration is the learning route. Only ask afterwards: \"Which improvement did you invent all by yourself?\" Notice the difference between a bit of grumbling (fine) and truly being stuck (then that one tip is allowed).",
    "bonus": "Do it again? Build the same thing once more, but with one hand ‚Äî or using only materials you can find within ten steps of your front door."
  },
  {
    "id": "verbeteren-04",
    "titel": "Make It Better than the AI",
    "superpower": "Verbeteren",
    "niveau": 4,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "25 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen"],
    "uitdaging": "AIs often give the FIRST answer that works. Not the best one. The gap between those two ‚Äî that's your territory.",
    "missie": "By the end, you'll have pushed an AI idea through at least three feedback rounds ‚Äî and you'll be able to point at exactly what got better because of YOUR steering.",
    "stappen": [
      "Ask the AI for an idea, for example a new playground game.",
      "Take it apart like a strict game designer: what's boring or illogical?",
      "Give targeted feedback: not 'better', but WHAT needs to be better.",
      "Have the AI adjust it and judge the new version.",
      "Repeat until you say: THIS is it ‚Äî and explain why."
    ],
    "samenwerken_met_ai": "The AI produces versions; you set the direction. Every round you steer with feedback ‚Äî and only your 'approved' counts as the finish line.",
    "ai_prompt": "I am [age] years old. You are my idea machine; I am the boss of quality. Think up an idea for [for example: a new playground game] in no more than 5 sentences. I will give feedback and you only change what I mention ‚Äî do not secretly change things I liked. After every version, ask: 'What needs to be better, boss?' and never say on your own that it's finished.",
    "eigen_keuze": "What's your measuring stick for 'good enough' ‚Äî and is it different from what the AI, your teacher or your parents would call good?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Setting the direction is a bigger power than producing ‚Äî machines make, humans decide what's good.",
    "reflectievraag": "Which feedback sentence of yours changed the most ‚Äî and what does that say about who did the real thinking here?",
    "zintuigen": ["tekenen", "vertellen"],
    "begeleiders_tip": "Help the child make feedback concrete: not 'more fun' but 'it needs something with running in it'. Ask: \"How can you tell version three is better than version one?\" Make sure the child picks the stopping moment ‚Äî even if you still see opportunities.",
    "bonus": "Do it again? Give yourself only three feedback rounds this time ‚Äî can you reach 'good enough' in fewer turns by giving sharper feedback?"
  },
  {
    "id": "verbeteren-05",
    "titel": "Master of the Final Version",
    "superpower": "Verbeteren",
    "niveau": 5,
    "categorie": "Maken",
    "werkvorm": ["Solo"],
    "tijdsduur": "30 min",
    "competenties": ["Itereren en Verbeteren", "Zelfvertrouwen", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "There is one word no AI can ever say for you: 'done'. Today you make something, improve it ‚Äî and say that word yourself, at exactly the right moment.",
    "missie": "By the end, you'll have a piece of work you're proud of, plus the hardest decision every maker faces behind you: this is the final version.",
    "stappen": [
      "Make something you want to be proud of: a drawing, story or build.",
      "Each improvement round, choose on purpose: do it myself, or ask an AI tip?",
      "Improve as much or as little as YOU want.",
      "Feel the moment coming: almost done...",
      "Speak the power word like a master: 'Done.' And explain why now."
    ],
    "samenwerken_met_ai": "You switch the AI on and off whenever you want ‚Äî your choice, every round. But there's one thing the AI can never do for you: decide that it's finished. That word is yours.",
    "ai_prompt": "I am [age] years old and I'm working on [what you're making]. These are my rules: if I ask for a tip, give exactly one (no more than 3 sentences). If I say 'I'll do this myself', reply only 'okay!'. Never ask me whether it's done yet and never suggest an improvement on your own ‚Äî the stopping moment belongs to me alone. Be honest if you're not sure about a tip.",
    "eigen_keuze": "How do you feel that something is done: it makes you happy, you can't think of anything to improve, or something else entirely?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî only when you want it",
    "wat_leer_je": "Stopping at the right moment isn't giving up ‚Äî it's the most powerful decision a maker can make.",
    "reflectievraag": "What would have happened if you'd KEPT improving ‚Äî and why can only a human feel when 'better' starts becoming 'worse'?",
    "zintuigen": ["kijken", "tekenen", "bouwen", "vertellen"],
    "begeleiders_tip": "Do NOT say 'you could still...' ‚Äî even kindly meant; the stopping moment is sacred. Ask: \"How did it feel to say 'done'?\" Notice whether the child stops out of satisfaction or out of tiredness ‚Äî that difference is worth a lovely conversation.",
    "bonus": "Do it again? Make something in ten minutes max and then declare it done ‚Äî is being satisfied quickly harder or easier than working on and on?"
  },
  {
    "id": "regie-voeren-01",
    "titel": "The AI On/Off Switch",
    "superpower": "Regie Voeren",
    "niveau": 1,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Samen"],
    "tijdsduur": "15 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "AI Bewustzijn"],
    "uitdaging": "Imagine every day had a switch. AI on, AI off. Giving a hug? Looking up a joke? Comforting someone? Your finger is on the switch.",
    "missie": "By the end, you'll be able to say for everyday jobs whether the AI switch goes on or off ‚Äî and you'll have discovered that some things only humans can do.",
    "stappen": [
      "Together, think up three ordinary things from your day.",
      "Play switch boss: for each job, flip the switch on or off.",
      "Defend your switch choice in one sentence.",
      "Find one thing together that must ALWAYS stay on 'off'.",
      "Tell each other why exactly that thing is human work."
    ],
    "samenwerken_met_ai": "Today you mostly talk ABOUT AI instead of WITH AI. Working the switch ‚Äî deciding where AI fits and where it doesn't ‚Äî is the real job, and that job is yours.",
    "ai_prompt": "For a child aged [age], make a list of 5 ordinary, familiar things from a kid's day (like having breakfast, looking something up, comforting a friend). Just the list, short and simple. Say NOTHING about whether AI could help with any of them ‚Äî that decision belongs entirely to the child and the grown-up.",
    "eigen_keuze": "Which job was the hardest to decide ‚Äî and what finally tipped the scales?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî but the switch work is yours",
    "wat_leer_je": "Some things are and will stay human ‚Äî and you can already point out which ones.",
    "reflectievraag": "Who should be allowed to touch that AI switch: you, your parents, or the AI itself ‚Äî and why never that last one?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "Deliberately slip 'human things' into the list: comforting, hugging, saying sorry. Ask: \"What would be lost if an AI did this?\" Watch for the moment the child feels the line for themselves ‚Äî that's the whole point of this card.",
    "bonus": "Do it again? Play it in reverse: think of three things everyone THINKS AI can't do ‚Äî and investigate whether that's really true."
  },
  {
    "id": "regie-voeren-02",
    "titel": "My Idea, AI Helps",
    "superpower": "Regie Voeren",
    "niveau": 2,
    "categorie": "Verbeelding",
    "werkvorm": ["Duo"],
    "tijdsduur": "20 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Creativiteit"],
    "uitdaging": "The party is yours. The theme is yours. The AI? It gets to help hang the streamers, at most ‚Äî if you ask.",
    "missie": "By the end, you'll have presented a plan that's completely your own, with exactly one small piece of AI help in it ‚Äî in the spot YOU pointed to.",
    "stappen": [
      "Think up your big idea yourself: a party, adventure or plan.",
      "As the one in charge, pick one small piece where help is allowed.",
      "Give the AI that one mini-job ‚Äî nothing more.",
      "From the AI's ideas, keep only what fits YOUR plan.",
      "Present your plan out loud, with your name on it."
    ],
    "samenwerken_met_ai": "You're the one in charge with the big idea; the AI is a helper for one small job. The plan carries your name ‚Äî as it should.",
    "ai_prompt": "I am [age] years old and THIS is my own plan: a [theme] party. You get exactly one mini-job from me: [for example: think up 4 names for party games]. Do only that, in no more than 5 short sentences. Stay out of the rest of my party ‚Äî no extra ideas about cake, decorations or anything else. This plan is mine.",
    "eigen_keuze": "Which piece did you hand over and which piece did you keep for yourself ‚Äî and what made THAT piece too important to give away?",
    "ai_tools": "an AI chat, together with a grown-up",
    "wat_leer_je": "Getting help is smart ‚Äî as long as you decide what for, how much and where.",
    "reflectievraag": "Did the plan still feel completely yours at the end ‚Äî and what happens to that feeling if you let the AI do more?",
    "zintuigen": ["luisteren", "vertellen"],
    "begeleiders_tip": "If the AI starts planning the whole party uninvited, let the child step in themselves: \"Hey, that wasn't your job!\" Then ask: \"Whose plan is this now?\" Watch the pride during the presentation ‚Äî that's your gauge.",
    "bonus": "Do it again? Make a plan where you ask the AI for NOTHING at all ‚Äî then compare: which plan felt more like yours?"
  },
  {
    "id": "regie-voeren-03",
    "titel": "Boss of the Boundaries",
    "superpower": "Regie Voeren",
    "niveau": 3,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "20‚Äì25 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen", "AI Bewustzijn"],
    "uitdaging": "Nowhere in the world is there a rulebook for how kids should use AI. So today you do what real founders do: you write it yourselves.",
    "missie": "By the end, you'll have three homemade AI rules on paper, tested in conversation ‚Äî with the whole team's signatures underneath.",
    "stappen": [
      "Discuss as lawmakers: what's okay and not okay to ask an AI?",
      "Write down three rules in your own words.",
      "Test each rule with an example: when does it really help?",
      "Ask the AI for a reaction ‚Äî as an opinion, not a verdict.",
      "Solemnly sign your rules, like a real law."
    ],
    "samenwerken_met_ai": "You write the law; the AI may give one opinion as an adviser. But an adviser never decides ‚Äî which rules stand is up to the team of humans.",
    "ai_prompt": "We are a team of kids aged [age] and we have written 3 rules ourselves for how we want to use AI: [rule 1], [rule 2], [rule 3]. You are our adviser, not our boss. For each rule, say in 1 or 2 friendly sentences what you think of it, and name at most one thing to think about. End with: 'But you decide ‚Äî they're your rules.'",
    "eigen_keuze": "Which rule is your number one ‚Äî the one that stands, no matter what the AI or anyone else thinks of it?",
    "ai_tools": "an AI chat, together with a grown-up ‚Äî as an adviser, not as the boss",
    "wat_leer_je": "Rules about AI are made by humans ‚Äî and you're already helping write them.",
    "reflectievraag": "If you could make rules for every kid in the country, which would you pick ‚Äî and who should check that AI sticks to human rules?",
    "zintuigen": ["luisteren", "vertellen", "onderzoeken"],
    "begeleiders_tip": "Make the signing grand ‚Äî a law deserves ceremony. Ask: \"What do we do if the AI disagrees with our rule?\" and enjoy the answer. Make sure the AI's reaction is treated as an opinion, not a correction.",
    "bonus": "Do it again? Write an AI rule for grown-ups this time ‚Äî and test it on a real grown-up. Do THEY stick to it?"
  },
  {
    "id": "regie-voeren-04",
    "titel": "The Screen-Free Master Test",
    "superpower": "Regie Voeren",
    "niveau": 4,
    "categorie": "Buitenwereld",
    "werkvorm": ["Solo"],
    "tijdsduur": "20‚Äì30 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen", "Zelfvertrouwen"],
    "uitdaging": "Knights had a sword test. Scouts had a campfire test. Your master test of today is ready and waiting: one job, zero screens, zero AI ‚Äî just you.",
    "missie": "By the end, you'll have completed a real job with only your own head and hands ‚Äî and you'll know from experience what you can do without help.",
    "stappen": [
      "Choose your master test: something to make, figure out or build.",
      "Declare it solemnly: I'm doing this with no screen and no AI.",
      "Complete the job on your own power, own ideas, own solutions.",
      "Notice along the way what was hard and what went surprisingly well.",
      "Judge for yourself afterwards: would AI have added anything ‚Äî or taken something away?"
    ],
    "samenwerken_met_ai": "You do the whole test deliberately without AI ‚Äî that's not a loss, it's the whole point. Only afterwards do you choose whether to look back on it with an AI.",
    "ai_prompt": "Only for afterwards, if you choose: I am [age] years old and I just completed my screen-free master test: [describe your job]. Ask me 3 short questions about how it went and what I discovered. Do not say anywhere that it would have been faster or better with AI ‚Äî this was the test WITHOUT you, and I passed it.",
    "eigen_keuze": "Which job deserves to be your master test: something easy that's sure to work, or something scary that makes you grow?",
    "ai_tools": "no AI needed ‚Äî you do this in the real world",
    "wat_leer_je": "Your own head and hands can do more than you think ‚Äî and now you know it from experience, not from hearsay.",
    "reflectievraag": "When would you deliberately choose 'without AI' from now on ‚Äî and why can only you make that choice for yourself?",
    "zintuigen": ["bouwen", "bewegen", "onderzoeken", "tekenen"],
    "begeleiders_tip": "Treat the test as an honor, not as screen punishment ‚Äî the words 'master test' really help. Ask afterwards: \"What could you do better than you expected?\" Don't jump in at the first bit of struggling; wrestling is part of the test.",
    "bonus": "Do it again? Pick a job you're certain you'd normally do WITH help ‚Äî the bigger the doubt beforehand, the bigger the master test."
  },
  {
    "id": "regie-voeren-05",
    "titel": "AI On or AI Off?",
    "superpower": "Regie Voeren",
    "niveau": 5,
    "categorie": "Mens & Maatschappij",
    "werkvorm": ["Team"],
    "tijdsduur": "25 min",
    "competenties": ["Menselijk Oordeel", "Verantwoordelijkheid", "Zelfstandig Oordelen"],
    "uitdaging": "Homework? Choosing a present? Solving an argument? In every situation, SOMEONE has to decide: AI in or AI out. Today that someone is you ‚Äî and your legs get a vote.",
    "missie": "By the end, you'll have made and defended a decision on five real situations ‚Äî and discovered that smart people are allowed to disagree.",
    "stappen": [
      "Read the first situation out loud, solemnly.",
      "Vote with your body: standing means AI on, sitting means AI off.",
      "Defend your choice like the Minister of AI Affairs.",
      "Listen to whoever chose differently ‚Äî maybe they'll win you over.",
      "Move to the next situation and vote again, round after round."
    ],
    "samenwerken_met_ai": "The AI may supply the situations, at most ‚Äî then it goes on mute. The voting, doubting and deciding is yours: exactly the work you must never outsource.",
    "ai_prompt": "Supply 5 short situations (1 sentence each) where a child aged [age] has to choose: use AI for this, or do it yourself? Mix easy choices (looking something up) with tricky ones (writing a sorry note, choosing a present). Give no answers, no hints and no opinion ‚Äî after that you're done and the kids decide everything themselves.",
    "eigen_keuze": "Which situation kept you hovering longest between standing and sitting ‚Äî and what is that doubt telling you?",
    "ai_tools": "an AI chat to think up the situations ‚Äî the choices you make yourselves",
    "wat_leer_je": "The smartest question isn't 'what can AI do?' but 'what do I WANT here: AI or me?' ‚Äî and you can ask that question now.",
    "reflectievraag": "Was there a situation where the whole group chose the same ‚Äî and does that mean it's right, or should someone keep doubting even then?",
    "zintuigen": ["vertellen", "bewegen"],
    "begeleiders_tip": "There is no wrong vote ‚Äî only weak and strong arguments. With every choice, ask: \"What would you miss if you did it the other way?\" Watch for kids who dare to change their mind after a good argument: name that as strength, not as flip-flopping.",
    "bonus": "Do it again? Let the kids invent the situations themselves this time ‚Äî the meanest edge cases they can think of ‚Äî and make the grown-ups vote too."
  }
];
